@echo off
rem ============================================================================
rem  BLDCB4.BAT — Build c4base.lib from CodeBase 4 source (99 .C files)
rem  Compiler: Borland C++ 3.1, large model
rem  Output:   \PCBCBASE\CODEBASE\BOR31\c4base.lib
rem ============================================================================
C:
set BC31PATH=\BC31
set CBSRC=\PCBCBASE\CODEBASE\SOURCE
set CBOBJ=\TMP\CBOBJ
set CBOUT=\PCBCBASE\CODEBASE\BOR31
set BCC=%BC31PATH%\BIN\BCC.EXE
set TLIB=%BC31PATH%\BIN\TLIB.EXE

rem Clean
if exist %CBOBJ%\NUL del %CBOBJ%\*.OBJ > NUL 2>&1
if not exist %CBOBJ%\NUL mkdir %CBOBJ%

rem Compile flags: large model, no warnings-as-errors, CodeBase source as include
set CFLAGS=-ml -c -w -I%BC31PATH%\INCLUDE -I%CBSRC% -n%CBOBJ%

echo Compiling CodeBase source (99 files)...

%BCC% %CFLAGS% %CBSRC%\B4BLOCK.C
%BCC% %CFLAGS% %CBSRC%\C4.C
%BCC% %CFLAGS% %CBSRC%\C4BCD.C
%BCC% %CFLAGS% %CBSRC%\C4CODE.C
%BCC% %CFLAGS% %CBSRC%\C4CONST.C
%BCC% %CFLAGS% %CBSRC%\D4APPEND.C
%BCC% %CFLAGS% %CBSRC%\D4CLOSE.C
%BCC% %CFLAGS% %CBSRC%\D4CREATE.C
%BCC% %CFLAGS% %CBSRC%\D4DATA.C
%BCC% %CFLAGS% %CBSRC%\D4DATE.C
%BCC% %CFLAGS% %CBSRC%\D4FIELD.C
%BCC% %CFLAGS% %CBSRC%\D4FLUSH.C
%BCC% %CFLAGS% %CBSRC%\D4FRESH.C
%BCC% %CFLAGS% %CBSRC%\D4GO.C
%BCC% %CFLAGS% %CBSRC%\D4INDEX.C
%BCC% %CFLAGS% %CBSRC%\D4LOCK.C
%BCC% %CFLAGS% %CBSRC%\D4OPEN.C
%BCC% %CFLAGS% %CBSRC%\D4OPT.C
%BCC% %CFLAGS% %CBSRC%\D4PACK.C
%BCC% %CFLAGS% %CBSRC%\D4POSITI.C
%BCC% %CFLAGS% %CBSRC%\D4SEEK.C
%BCC% %CFLAGS% %CBSRC%\D4SKIP.C
%BCC% %CFLAGS% %CBSRC%\D4TAG.C
%BCC% %CFLAGS% %CBSRC%\D4UNLOCK.C
%BCC% %CFLAGS% %CBSRC%\D4WRITE.C
%BCC% %CFLAGS% %CBSRC%\D4ZAP.C
%BCC% %CFLAGS% %CBSRC%\E4CALC.C
%BCC% %CFLAGS% %CBSRC%\E4ERROR.C
%BCC% %CFLAGS% %CBSRC%\E4EXPR.C
%BCC% %CFLAGS% %CBSRC%\E4FUNCTI.C
%BCC% %CFLAGS% %CBSRC%\E4NOT_S.C
%BCC% %CFLAGS% %CBSRC%\E4PARSE.C
%BCC% %CFLAGS% %CBSRC%\F4ASS_F.C
%BCC% %CFLAGS% %CBSRC%\F4CHAR.C
%BCC% %CFLAGS% %CBSRC%\F4CLOSE.C
%BCC% %CFLAGS% %CBSRC%\F4CREATE.C
%BCC% %CFLAGS% %CBSRC%\F4DOUBLE.C
%BCC% %CFLAGS% %CBSRC%\F4FIELD.C
%BCC% %CFLAGS% %CBSRC%\F4FILE.C
%BCC% %CFLAGS% %CBSRC%\F4FILESE.C
%BCC% %CFLAGS% %CBSRC%\F4FLAG.C
%BCC% %CFLAGS% %CBSRC%\F4FLUSH.C
%BCC% %CFLAGS% %CBSRC%\F4INFO.C
%BCC% %CFLAGS% %CBSRC%\F4INT.C
%BCC% %CFLAGS% %CBSRC%\F4LOCK.C
%BCC% %CFLAGS% %CBSRC%\F4LONG.C
%BCC% %CFLAGS% %CBSRC%\F4MEMO.C
%BCC% %CFLAGS% %CBSRC%\F4OPEN.C
%BCC% %CFLAGS% %CBSRC%\F4OPT.C
%BCC% %CFLAGS% %CBSRC%\F4PTR.C
%BCC% %CFLAGS% %CBSRC%\F4STR.C
%BCC% %CFLAGS% %CBSRC%\F4TEMP.C
%BCC% %CFLAGS% %CBSRC%\F4TRUE.C
%BCC% %CFLAGS% %CBSRC%\F4WRITE.C
%BCC% %CFLAGS% %CBSRC%\I4ADD.C
%BCC% %CFLAGS% %CBSRC%\I4ADDTAG.C
%BCC% %CFLAGS% %CBSRC%\I4CHECK.C
%BCC% %CFLAGS% %CBSRC%\I4CREATE.C
%BCC% %CFLAGS% %CBSRC%\I4DUMP.C
%BCC% %CFLAGS% %CBSRC%\I4INDEX.C
%BCC% %CFLAGS% %CBSRC%\I4INFO.C
%BCC% %CFLAGS% %CBSRC%\I4INIT.C
%BCC% %CFLAGS% %CBSRC%\I4KEY.C
%BCC% %CFLAGS% %CBSRC%\I4LOCK.C
%BCC% %CFLAGS% %CBSRC%\I4NTAG.C
%BCC% %CFLAGS% %CBSRC%\I4POSITI.C
%BCC% %CFLAGS% %CBSRC%\I4REMOVE.C
%BCC% %CFLAGS% %CBSRC%\I4TAG.C
%BCC% %CFLAGS% %CBSRC%\L4LINK.C
%BCC% %CFLAGS% %CBSRC%\L4LOCK_C.C
%BCC% %CFLAGS% %CBSRC%\M4CHECK.C
%BCC% %CFLAGS% %CBSRC%\M4CREATE.C
%BCC% %CFLAGS% %CBSRC%\M4FILE.C
%BCC% %CFLAGS% %CBSRC%\M4MAP.C
%BCC% %CFLAGS% %CBSRC%\M4MEMO.C
%BCC% %CFLAGS% %CBSRC%\M4MEMORY.C
%BCC% %CFLAGS% %CBSRC%\MEM.C
%BCC% %CFLAGS% %CBSRC%\O4OPT.C
%BCC% %CFLAGS% %CBSRC%\R4CODE.C
%BCC% %CFLAGS% %CBSRC%\R4DRIVER.C
%BCC% %CFLAGS% %CBSRC%\R4GROUP.C
%BCC% %CFLAGS% %CBSRC%\R4LOG.C
%BCC% %CFLAGS% %CBSRC%\R4OBJECT.C
%BCC% %CFLAGS% %CBSRC%\R4REINDE.C
%BCC% %CFLAGS% %CBSRC%\R4REINDX.C
%BCC% %CFLAGS% %CBSRC%\R4RELATE.C
%BCC% %CFLAGS% %CBSRC%\R4REPORT.C
%BCC% %CFLAGS% %CBSRC%\R4SAVE.C
%BCC% %CFLAGS% %CBSRC%\R4SAVE_M.C
%BCC% %CFLAGS% %CBSRC%\R4STYLES.C
%BCC% %CFLAGS% %CBSRC%\R4TEXT.C
%BCC% %CFLAGS% %CBSRC%\R4TOTAL.C
%BCC% %CFLAGS% %CBSRC%\S4INIT.C
%BCC% %CFLAGS% %CBSRC%\S4INITFR.C
%BCC% %CFLAGS% %CBSRC%\S4NEXT.C
%BCC% %CFLAGS% %CBSRC%\S4QUICK.C
%BCC% %CFLAGS% %CBSRC%\S4SORT.C
%BCC% %CFLAGS% %CBSRC%\U4NAME.C
%BCC% %CFLAGS% %CBSRC%\U4UTIL.C

echo.
echo Compile phase done. Counting OBJs...
dir %CBOBJ%\*.OBJ > \TMP\C4OBJS.TXT

rem Build the library with TLIB using one-at-a-time adds (DOS cmd line limit)
if not exist %CBOUT%\NUL mkdir %CBOUT%
if exist %CBOUT%\c4base.lib del %CBOUT%\c4base.lib
if exist %CBOUT%\C4BASE.LIB del %CBOUT%\C4BASE.LIB
if exist %CBOUT%\C4BASE.BAK del %CBOUT%\C4BASE.BAK

echo Building c4base.lib (adding modules one at a time)...
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\B4BLOCK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\C4.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\C4BCD.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\C4CODE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\C4CONST.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4APPEND.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4CLOSE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4CREATE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4DATA.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4DATE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4FIELD.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4FLUSH.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4FRESH.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4GO.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4INDEX.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4LOCK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4OPEN.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4OPT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4PACK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4POSITI.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4SEEK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4SKIP.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4TAG.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4UNLOCK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4WRITE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\D4ZAP.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\E4CALC.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\E4ERROR.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\E4EXPR.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\E4FUNCTI.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\E4NOT_S.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\E4PARSE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4ASS_F.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4CHAR.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4CLOSE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4CREATE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4DOUBLE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4FIELD.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4FILE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4FILESE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4FLAG.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4FLUSH.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4INFO.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4INT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4LOCK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4LONG.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4MEMO.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4OPEN.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4OPT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4PTR.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4STR.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4TEMP.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4TRUE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\F4WRITE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4ADD.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4ADDTAG.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4CHECK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4CREATE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4DUMP.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4INDEX.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4INFO.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4INIT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4KEY.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4LOCK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4NTAG.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4POSITI.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4REMOVE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\I4TAG.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\L4LINK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\L4LOCK_C.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\M4CHECK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\M4CREATE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\M4FILE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\M4MAP.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\M4MEMO.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\M4MEMORY.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\MEM.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\O4OPT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4CODE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4DRIVER.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4GROUP.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4LOG.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4OBJECT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4REINDE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4REINDX.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4RELATE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4REPORT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4SAVE.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4SAVE_M.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4STYLES.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4TEXT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\R4TOTAL.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\S4INIT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\S4INITFR.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\S4NEXT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\S4QUICK.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\S4SORT.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\U4NAME.OBJ
%TLIB% %CBOUT%\c4base.lib +%CBOBJ%\U4UTIL.OBJ

echo.
if exist %CBOUT%\C4BASE.LIB echo SUCCESS: c4base.lib built
if exist %CBOUT%\C4BASE.LIB dir %CBOUT%\C4BASE.LIB
if not exist %CBOUT%\C4BASE.LIB echo FAILED: c4base.lib not created

echo DONE > \TMP\C4DONE.TXT
