; PCBTHUNK.ASM - C++/pascal name bridge for PCBoard library functions
; Written by: hexadecimal, v0.036
.MODEL LARGE

EXTRN PCBINIT:FAR
EXTRN FINDUSER:FAR
EXTRN TICKDELAY:FAR
EXTRN GETCONFRECORD:FAR
EXTRN PUTCONFRECORD:FAR
EXTRN OPENCNAMES:FAR
EXTRN CLOSECNAMES:FAR
EXTRN OPENUSERSFILE:FAR
EXTRN CLOSEUSERSFILE:FAR
EXTRN OPENUSERSINFFILE:FAR
EXTRN CLOSEUSERSINFFILE:FAR
EXTRN DOSERROR:FAR
EXTRN PUTMESSAGEWAITING:FAR
EXTRN BUILDGENEXTHEADER:FAR
EXTRN FREEHDRS:FAR
EXTRN BUILDEXTHEADER:FAR
EXTRN CLOSEMESSAGEBASE:FAR
EXTRN OPENMESSAGEBASE:FAR
EXTRN SAVETOMSGBASE:FAR
EXTRN MAKEMSGHEADER:FAR
EXTRN DOSFREAD:FAR
EXTRN SENDSTR:FAR
EXTRN SENDBYTE:FAR
EXTRN CLOSEMODEM:FAR
EXTRN SLOWSENDTOMODEM:FAR
EXTRN OPENMODEM:FAR
EXTRN INITPORT:FAR
EXTRN RETRYCOUNT:FAR
EXTRN PRINTLN:FAR

.DATA
PUBLIC _DebugLevel
_DebugLevel DW 0
PUBLIC __KbdStatus
__KbdStatus DW 0

.CODE

PUBLIC @PCBINIT$QV
PUBLIC @FINDUSER$QNUC
PUBLIC @TICKDELAY$QI
PUBLIC @GETCONFRECORD$QUIN11PCBCONFTYPE
PUBLIC @PUTCONFRECORD$QUIN11PCBCONFTYPE
PUBLIC @OPENCNAMES$QV
PUBLIC @CLOSECNAMES$QV
PUBLIC @OPENUSERSFILE$QV
PUBLIC @CLOSEUSERSFILE$QV
PUBLIC @OPENUSERSINFFILE$QV
PUBLIC @CLOSEUSERSINFFILE$QV
PUBLIC @DOSERROR$QNUCI
PUBLIC @PUTMESSAGEWAITING$QUIL
PUBLIC @BUILDGENEXTHEADER$QNUCT1
PUBLIC @FREEHDRS$QV
PUBLIC @BUILDEXTHEADER$Q10EXTHDRTYPENUCUC
PUBLIC @CLOSEMESSAGEBASE$QN11MSGBASETYPE
PUBLIC @OPENMESSAGEBASE$QUSN11PCBCONFTYPEN11MSGBASETYPE11OPENMSGTYPE
PUBLIC @SAVETOMSGBASE$QUSN11PCBCONFTYPEN11MSGBASETYPEN13MSGHEADERTYPCG
PUBLIC @MAKEMSGHEADER$QN13MSGHEADERTYPEUCUSNUCT4T4LUST4UCT4T4T4UC
PUBLIC @DOSFREAD$QNVUIN7DOSFILE
PUBLIC @SENDSTR$QNUCI
PUBLIC @SENDBYTE$QUC
PUBLIC @CLOSEMODEM$QUC
PUBLIC @SLOWSENDTOMODEM$QNUC
PUBLIC @OPENMODEM$Q8SHOWTYPE
PUBLIC @INITPORT$QV
PUBLIC @RETRYCOUNT$QUINUCT2
PUBLIC @PRINTLN$QNUC

@PCBINIT$QV:                    JMP PCBINIT
@FINDUSER$QNUC:                 JMP FINDUSER
@TICKDELAY$QI:                   JMP TICKDELAY
@GETCONFRECORD$QUIN11PCBCONFTYPE: JMP GETCONFRECORD
@PUTCONFRECORD$QUIN11PCBCONFTYPE: JMP PUTCONFRECORD
@OPENCNAMES$QV:                  JMP OPENCNAMES
@CLOSECNAMES$QV:                 JMP CLOSECNAMES
@OPENUSERSFILE$QV:               JMP OPENUSERSFILE
@CLOSEUSERSFILE$QV:              JMP CLOSEUSERSFILE
@OPENUSERSINFFILE$QV:            JMP OPENUSERSINFFILE
@CLOSEUSERSINFFILE$QV:           JMP CLOSEUSERSINFFILE
@DOSERROR$QNUCI:                JMP DOSERROR
@PUTMESSAGEWAITING$QUIL:        JMP PUTMESSAGEWAITING
@BUILDGENEXTHEADER$QNUCT1:      JMP BUILDGENEXTHEADER
@FREEHDRS$QV:                    JMP FREEHDRS
@BUILDEXTHEADER$Q10EXTHDRTYPENUCUC: JMP BUILDEXTHEADER
@CLOSEMESSAGEBASE$QN11MSGBASETYPE: JMP CLOSEMESSAGEBASE
@OPENMESSAGEBASE$QUSN11PCBCONFTYPEN11MSGBASETYPE11OPENMSGTYPE: JMP OPENMESSAGEBASE
@SAVETOMSGBASE$QUSN11PCBCONFTYPEN11MSGBASETYPEN13MSGHEADERTYPCG: JMP SAVETOMSGBASE
@MAKEMSGHEADER$QN13MSGHEADERTYPEUCUSNUCT4T4LUST4UCT4T4T4UC: JMP MAKEMSGHEADER
@DOSFREAD$QNVUIN7DOSFILE:       JMP DOSFREAD
@SENDSTR$QNUCI:                 JMP SENDSTR
@SENDBYTE$QUC:                  JMP SENDBYTE
@CLOSEMODEM$QUC:                JMP CLOSEMODEM
@SLOWSENDTOMODEM$QNUC:          JMP SLOWSENDTOMODEM
@OPENMODEM$Q8SHOWTYPE:           JMP OPENMODEM
@INITPORT$QV:                    JMP INITPORT
@RETRYCOUNT$QUINUCT2:            JMP RETRYCOUNT
@PRINTLN$QNUC:                   JMP PRINTLN

END
