/o- \proj\pcb\obj\tc30\noscroll.obj+
/o- \proj\lib\bcdos\tc30\misc\large\swap.obj+
/o- \proj\pcb\obj\tc30\pcboard.obj+
/o- \proj\pcb\obj\tc30\overlay.obj+
/o- \proj\pcb\obj\tc30\inkey.obj+
/o- \proj\pcb\obj\tc30\memory.obj+
/o- \proj\pcb\obj\tc30\modem.obj+
/o- \proj\pcb\obj\tc30\dosopen.obj+
/o- \proj\pcb\obj\tc30\dosclose.obj+
/o- \proj\pcb\obj\tc30\dosread.obj+
/o- \proj\pcb\obj\tc30\doswrite.obj+
/o- \proj\pcb\obj\tc30\dostime.obj+
/o- \proj\pcb\obj\tc30\ansi.obj+
/o- \proj\pcb\obj\tc30\async.obj+
/o- \proj\pcb\obj\tc30\bgkey.obj+
/o- \proj\pcb\obj\tc30\cutil.obj+
/o- \proj\pcb\obj\tc30\memmove.obj+
/o- \proj\pcb\obj\tc30\timer.obj+
/o- \proj\pcb\obj\tc30\display.obj+
/o- \proj\pcb\obj\tc30\xlate.obj+
/o- \proj\pcb\obj\tc30\devioctl.obj+
/o- \proj\pcb\obj\tc30\VAR.obj+
/o- \proj\pcb\obj\tc30\ticdelay.obj+
/o+ \proj\pcb\obj\tc30\init.obj+
/o+ \proj\pcb\obj\tc30\pcbtext.obj+
/o+ \proj\pcb\obj\tc30\language.obj+
/o+ \proj\pcb\obj\tc30\sys.obj+
/o+ \proj\pcb\obj\tc30\log.obj+
/o+ \proj\pcb\obj\tc30\token.obj+
/o+ \proj\pcb\obj\tc30\users.obj+
/o+ \proj\pcb\obj\tc30\usernet.obj+
/o+ \proj\pcb\obj\tc30\stats.obj+
/o+ \proj\pcb\obj\tc30\screen.obj+
/o+ \proj\pcb\obj\tc30\callwait.obj+
/o+ \proj\pcb\obj\tc30\account.obj+
/o+ \proj\pcb\obj\tc30\blt.obj+
/o+ \proj\pcb\obj\tc30\capture.obj+
/o+ \proj\pcb\obj\tc30\chat.obj+
/o+ \proj\pcb\obj\tc30\cmds.obj+
/o+ \proj\pcb\obj\tc30\command.obj+
/o+ \proj\pcb\obj\tc30\crc32.obj+
/o+ \proj\pcb\obj\tc30\confrnce.obj+
/o+ \proj\pcb\obj\tc30\copyfile.obj+
/o+ \proj\pcb\obj\tc30\dir.obj+
/o+ \proj\pcb\obj\tc30\diz.obj+
/o+ \proj\pcb\obj\tc30\dlpath.obj+
/o+ \proj\pcb\obj\tc30\doors.obj+
/o+ \proj\pcb\obj\tc30\event.obj+
/o+ \proj\pcb\obj\tc30\data.obj+
/o+ \proj\pcb\obj\tc30\passthru.obj+
/o+ \proj\pcb\obj\tc30\fidomenu.obj+
/o+ \proj\pcb\obj\tc30\fidomisc.obj+
/o+ \proj\pcb\obj\tc30\filelist.obj+
/o+ \proj\pcb\obj\tc30\files.obj+
/o+ \proj\pcb\obj\tc30\help.obj+
/o+ \proj\pcb\obj\tc30\index.obj+
/o+ \proj\pcb\obj\tc30\input.obj+
/o+ \proj\pcb\obj\tc30\logview.obj+
/o+ \proj\pcb\obj\tc30\login.obj+
/o+ \proj\pcb\obj\tc30\msgbase.obj+
/o+ \proj\pcb\obj\tc30\messages.obj+
/o+ \proj\pcb\obj\tc30\misc.obj+
/o+ \proj\pcb\obj\tc30\modemasy.obj+
/o+ \proj\pcb\obj\tc30\modemfos.obj+
/o+ \proj\pcb\obj\tc30\modemdrv.obj+
/o+ \proj\pcb\obj\tc30\modemos2.obj+
/o+ \proj\pcb\obj\tc30\msgenter.obj+
/o+ \proj\pcb\obj\tc30\msgread.obj+
/o+ \proj\pcb\obj\tc30\msgscan.obj+
/o+ \proj\pcb\obj\tc30\newchat.obj+
/o+ \proj\pcb\obj\tc30\node.obj+
/o+ \proj\pcb\obj\tc30\pcbtoss.obj+
/o+ \proj\pcb\obj\tc30\tossmisc.obj+
/o+ \proj\pcb\obj\tc30\ratio.obj+
/o+ \proj\pcb\obj\tc30\recycle.obj+
/o+ \proj\pcb\obj\tc30\script.obj+
/o+ \proj\pcb\obj\tc30\scrlback.obj+
/o+ \proj\pcb\obj\tc30\settings.obj+
/o+ \proj\pcb\obj\tc30\shell.obj+
/o+ \proj\pcb\obj\tc30\showerr.obj+
/o+ \proj\pcb\obj\tc30\status.obj+
/o+ \proj\pcb\obj\tc30\transfer.obj+
/o+ \proj\pcb\obj\tc30\userstat.obj+
/o+ \proj\pcb\obj\tc30\usersys.obj+
/o+ \proj\pcb\obj\tc30\userscan.obj+
/o+ \proj\pcb\obj\tc30\usrmaint.obj+
/o+ \proj\pcb\obj\tc30\FILESTUB.obj+
/o+ \proj\pcb\obj\tc30\LABEL.obj+
/o+ \proj\pcb\obj\tc30\SCRMISC.obj+
/o+ \proj\pcb\obj\tc30\NEWSCR.obj+
/o+ \proj\pcb\obj\tc30\PCBMISC.obj+
/o+ \proj\pcb\obj\tc30\SCREXEC.obj+
/o+ \proj\pcb\obj\tc30\EVALP.obj+
/o+ \proj\pcb\obj\tc30\EXECDB.obj+
/o+ \proj\pcb\obj\tc30\MENU.obj+
/o+ \proj\pcb\obj\tc30\LRAND.obj+
/o+ \proj\pcb\obj\tc30\DBASE.obj+
/o+ \proj\pcb\obj\tc30\recemsi.obj+
/o+ \proj\pcb\obj\tc30\fconfig.obj+
/o+ \proj\pcb\obj\tc30\hex.obj+
/o+ \proj\pcb\obj\tc30\crc-16f.obj+
/o+ \proj\pcb\obj\tc30\xmitemsi.obj+
/o+ \proj\pcb\obj\tc30\fidofunc.obj+
/o+ \proj\pcb\obj\tc30\recwazoo.obj+
/o+ \proj\pcb\obj\tc30\umwf.obj+
/o+ \proj\pcb\obj\tc30\pcbmsgs.obj+
/o- \proj\pcb\obj\tc30\msgstub.obj+
/o+ \proj\pcb\obj\tc30\fidoque.obj+
/o+ \proj\pcb\obj\tc30\fidomsg.obj+
/o+ \proj\pcb\obj\tc30\seenby.obj+
/o+ \proj\pcb\obj\tc30\dupechec.obj+
/o+ \proj\lib\bcdos\tc30\misc\large\bmsearch.obj+
/o+ \proj\lib\bcdos\tc30\misc\large\psearch.obj+
/o+ \proj\lib\bcdos\tc30\misc\large\julian.obj+
/o+ \proj\lib\bcdos\tc30\misc\large\ctod.obj+
/o+ \proj\lib\bcdos\tc30\misc\large\append.obj+
/o+ \proj\lib\bcdos\tc30\misc\large\proper.obj+
/o+ \proj\lib\bcdos\tc30\misc\large\diskfree.obj+
/o+ \proj\lib\bcdos\tc30\misc\large\subst.obj+
/o+ \proj\lib\bcdos\tc30\dos\large\doserror.obj+
/o+ \proj\lib\bcdos\tc30\dos\large\dosfread.obj+
/o+ \proj\lib\bcdos\tc30\dos\large\dosfgets.obj+
/o+ \proj\lib\bcdos\tc30\dos\large\dosfugts.obj+
/o+ \proj\lib\bcdos\tc30\pcb\large\datafil2.obj+
/o+ \proj\lib\bcdos\tc30\pcb\large\cnames.obj+
/o+ \proj\lib\bcdos\tc30\country\large\country.obj+
/o+ \proj\lib\bcdos\tc30\screen\large\getmode.obj+
/o+ \proj\lib\bcdos\tc30\screen\large\box.obj
