/o- obj\bc31\noscroll.obj+
/o- ..\lib\bcdos\bc31\misc\large.386\swap.obj+
/o- obj\bc31\pcboard.obj+
/o- obj\bc31\overlay.obj+
/o- obj\bc31\inkey.obj+
/o- obj\bc31\memory.obj+
/o- obj\bc31\modem.obj+
/o- obj\bc31\dosopen.obj+
/o- obj\bc31\dosclose.obj+
/o- obj\bc31\dosread.obj+
/o- obj\bc31\doswrite.obj+
/o- obj\bc31\dostime.obj+
/o- obj\bc31\ansi.obj+
/o- obj\bc31\async.obj+
/o- obj\bc31\bgkey.obj+
/o- obj\bc31\cutil.obj+
/o- obj\bc31\memmove.obj+
/o- obj\bc31\timer.obj+
/o- obj\bc31\display.obj+
/o- obj\bc31\xlate.obj+
/o- obj\bc31\devioctl.obj+
/o- obj\bc31\var.obj+
/o- obj\bc31\ticdelay.obj+
/o  obj\bc31\init.obj+
/o  obj\bc31\pcbtext.obj+
/o  obj\bc31\language.obj+
/o  obj\bc31\sys.obj+
/o  obj\bc31\log.obj+
/o  obj\bc31\token.obj+
/o  obj\bc31\users.obj+
/o  obj\bc31\usernet.obj+
/o  obj\bc31\stats.obj+
/o  obj\bc31\screen.obj+
/o  obj\bc31\callwait.obj+
/o  obj\bc31\account.obj+
/o  obj\bc31\blt.obj+
/o  obj\bc31\capture.obj+
/o  obj\bc31\chat.obj+
/o  obj\bc31\cmds.obj+
/o  obj\bc31\command.obj+
/o  obj\bc31\crc32.obj+
/o  obj\bc31\confrnce.obj+
/o  obj\bc31\copyfile.obj+
/o  obj\bc31\dir.obj+
/o  obj\bc31\diz.obj+
/o  obj\bc31\dlpath.obj+
/o  obj\bc31\doors.obj+
/o  obj\bc31\event.obj+
/o  obj\bc31\data.obj+
/o  obj\bc31\passthru.obj+
/o  obj\bc31\fidomenu.obj+
/o  obj\bc31\fidomisc.obj+
/o  obj\bc31\filelist.obj+
/o  obj\bc31\files.obj+
/o  obj\bc31\help.obj+
/o  obj\bc31\index.obj+
/o  obj\bc31\input.obj+
/o  obj\bc31\logview.obj+
/o  obj\bc31\login.obj+
/o  obj\bc31\msgbase.obj+
/o  obj\bc31\messages.obj+
/o  obj\bc31\misc.obj+
/o  obj\bc31\modemasy.obj+
/o  obj\bc31\modemfos.obj+
/o  obj\bc31\modemdrv.obj+
/o  obj\bc31\modemos2.obj+
/o  obj\bc31\msgenter.obj+
/o  obj\bc31\msgread.obj+
/o  obj\bc31\msgscan.obj+
/o  obj\bc31\newchat.obj+
/o  obj\bc31\node.obj+
/o  obj\bc31\pcbtoss.obj+
/o  obj\bc31\tossmisc.obj+
/o  obj\bc31\ratio.obj+
/o  obj\bc31\recycle.obj+
/o  obj\bc31\script.obj+
/o  obj\bc31\scrlback.obj+
/o  obj\bc31\settings.obj+
/o  obj\bc31\shell.obj+
/o  obj\bc31\showerr.obj+
/o  obj\bc31\status.obj+
/o  obj\bc31\transfer.obj+
/o  obj\bc31\userstat.obj+
/o  obj\bc31\usersys.obj+
/o  obj\bc31\userscan.obj+
/o  obj\bc31\usrmaint.obj+
/o  obj\bc31\filestub.obj+
/o  obj\bc31\label.obj+
/o  obj\bc31\scrmisc.obj+
/o  obj\bc31\newscr.obj+
/o  obj\bc31\pcbmisc.obj+
/o  obj\bc31\screxec.obj+
/o  obj\bc31\evalp.obj+
/o  obj\bc31\execdb.obj+
/o  obj\bc31\menu.obj+
/o  obj\bc31\lrand.obj+
/o  obj\bc31\dbase.obj+
/o  obj\bc31\recemsi.obj+
/o  obj\bc31\fconfig.obj+
/o  obj\bc31\hex.obj+
/o  obj\bc31\crc-16f.obj+
/o  obj\bc31\xmitemsi.obj+
/o  obj\bc31\fidofunc.obj+
/o  obj\bc31\recwazoo.obj+
/o  obj\bc31\umwf.obj+
/o  obj\bc31\pcbmsgs.obj+
/o- obj\bc31\msgstub.obj+
/o  obj\bc31\fidoque.obj+
/o  obj\bc31\fidomsg.obj+
/o  obj\bc31\seenby.obj+
/o  obj\bc31\dupechec.obj+
/o  ..\lib\bcdos\bc31\misc\large.386\bmsearch.obj+
/o  ..\lib\bcdos\bc31\misc\large.386\psearch.obj+
/o  ..\lib\bcdos\bc31\misc\large.386\julian.obj+
/o  ..\lib\bcdos\bc31\misc\large.386\ctod.obj+
/o  ..\lib\bcdos\bc31\misc\large.386\diskfree.obj+
/o  ..\lib\bcdos\bc31\misc\large.386\append.obj+
/o  ..\lib\bcdos\bc31\misc\large.386\proper.obj+
/o  ..\lib\bcdos\bc31\misc\large.386\subst.obj+
/o  ..\lib\bcdos\bc31\dos\large.386\doserror.obj+
/o  ..\lib\bcdos\bc31\dos\large.386\dosfread.obj+
/o  ..\lib\bcdos\bc31\dos\large.386\dosfgets.obj+
/o  ..\lib\bcdos\bc31\dos\large.386\dosfugts.obj+
/o  ..\lib\bcdos\bc31\pcb\large.386\datafil2.obj+
/o  ..\lib\bcdos\bc31\pcb\large.386\cnames.obj+
/o  ..\lib\bcdos\bc31\country\large.386\country.obj+
/o  ..\lib\bcdos\bc31\screen\large.386\getmode.obj+
/o  ..\lib\bcdos\bc31\screen\large.386\box.obj
