# DOSBox-X config for LANtastic v6
# Requires patched binary built from dosbox-x-src-patched.7z

[cpu]
cputype=pentium

[serial]
serial2=disabled

[ne2000]
ne2000=true
nicbase=300
nicirq=3
macaddr=AC:DE:48:88:99:AA
backend=slirp
