@echo off
if not '%BCROOT%' == '' goto DONE
  set BCROOT=\BCOS2
  set INCLUDE=%BCROOT%\INCLUDE
  set LIBPATH=%BCROOT%\LIB
  set COMPILER=%BCROOT%\BIN\BCC.EXE
  set LINKER=%BCROOT%\BIN\TLINK.EXE
  set MAKE=%BCROOT%\BIN\MAKE.EXE
  set LIBSDIR=\LIBS

:done
