/* ====================================================================
 * cytrace.h — WPP Tracing Definitions for CYPORT Driver
 * ====================================================================
 * Windows Software Trace Preprocessor (WPP) configuration.
 * WPP generates ETW (Event Tracing for Windows) events that can be
 * captured with TraceView, logman, or xperf and analyzed in WPA.
 *
 * HOW WPP WORKS:
 *   1. We define trace GUIDs and message functions here
 *   2. WPP preprocessor (run by build system) scans .c files for
 *      DoTraceMessage() calls and generates .tmh files
 *   3. At runtime, a trace controller enables our GUID and we
 *      emit events to an ETL file
 *   4. tracefmt/tracepdb decode the ETL using PDB symbols
 *
 * TO CAPTURE TRACES:
 *   tracelog -start cyport -guid #A1B2C3D4-... -f cyport.etl
 *   <reproduce issue>
 *   tracelog -stop cyport
 *   tracefmt cyport.etl -p . -o cyport.txt
 *
 * ADVANTAGES OVER DbgPrint:
 *   - Zero overhead when tracing is off (flag check + jmp)
 *   - Structured data (not just strings)
 *   - Captured to file (no debugger required)
 *   - Timestamps with 100ns resolution
 *   - Can trace at DIRQL (ISR-safe)
 *   - Post-mortem analysis
 * ====================================================================
 */

#ifndef CYTRACE_H
#define CYTRACE_H

/* ====================================================================
 * TRACE GUID
 * ====================================================================
 * Every WPP-traced driver needs a unique GUID. This GUID is used
 * by trace controllers (tracelog, TraceView) to enable/disable our
 * trace provider.
 *
 * Generated once, never changes for the lifetime of the driver.
 * ==================================================================== */

/* {A7E3B4C1-9F2D-4A8E-B5C6-7D1E8F3A2B4C} */
#define WPP_CONTROL_GUIDS                                              \
    WPP_DEFINE_CONTROL_GUID(                                           \
        CyportTraceGuid,                                               \
        (A7E3B4C1,9F2D,4A8E,B5C6,7D1E8F3A2B4C),                      \
        WPP_DEFINE_BIT(CYPORT_INIT)       /* bit 0: initialization  */ \
        WPP_DEFINE_BIT(CYPORT_PNP)        /* bit 1: PnP events      */ \
        WPP_DEFINE_BIT(CYPORT_POWER)      /* bit 2: power events     */ \
        WPP_DEFINE_BIT(CYPORT_IOCTL)      /* bit 3: IOCTL dispatch   */ \
        WPP_DEFINE_BIT(CYPORT_READ)       /* bit 4: read path        */ \
        WPP_DEFINE_BIT(CYPORT_WRITE)      /* bit 5: write path       */ \
        WPP_DEFINE_BIT(CYPORT_ISR)        /* bit 6: ISR/DPC          */ \
        WPP_DEFINE_BIT(CYPORT_HW)         /* bit 7: hardware access  */ \
        WPP_DEFINE_BIT(CYPORT_FLOW)       /* bit 8: flow control     */ \
        WPP_DEFINE_BIT(CYPORT_MODEM)      /* bit 9: modem signals    */ \
    )

/* ====================================================================
 * TRACE LEVELS
 * ====================================================================
 * WPP uses standard ETW levels. We map our debug levels to these.
 * ==================================================================== */

#define CYPORT_LEVEL_CRITICAL   TRACE_LEVEL_CRITICAL    /* 1 */
#define CYPORT_LEVEL_ERROR      TRACE_LEVEL_ERROR       /* 2 */
#define CYPORT_LEVEL_WARNING    TRACE_LEVEL_WARNING     /* 3 */
#define CYPORT_LEVEL_INFO       TRACE_LEVEL_INFORMATION /* 4 */
#define CYPORT_LEVEL_VERBOSE    TRACE_LEVEL_VERBOSE     /* 5 */


/* ====================================================================
 * TRACE MACROS
 * ====================================================================
 * Usage examples:
 *
 *   TraceEvents(CYPORT_LEVEL_INFO, CYPORT_INIT,
 *               "DriverEntry: found %d chips", numChips);
 *
 *   TraceEvents(CYPORT_LEVEL_VERBOSE, CYPORT_HW,
 *               "RD chip=%d reg=0x%03X val=0x%02X",
 *               chipIdx, regOffset, regValue);
 *
 *   TraceEvents(CYPORT_LEVEL_ERROR, CYPORT_ISR,
 *               "ISR: unexpected IIR value 0x%02X on chip %d",
 *               iirVal, chipIdx);
 *
 * When WPP is not available (e.g., cross-compilation), these
 * fall back to DbgPrint via the cydebug.h macros.
 * ==================================================================== */

#ifdef WPP_ENABLED

/* WPP_INIT_TRACING and WPP_CLEANUP are called from DriverEntry
 * and DriverUnload respectively. The build system generates the
 * actual implementations. */

/* The trace message function. WPP preprocessor will replace these
 * with efficient binary logging calls. */

/* Note: The actual TraceEvents definition is generated by the WPP
 * preprocessor into cyport.tmh. We just declare the usage pattern
 * here for documentation. */

#else  /* WPP not available — fall back to DbgPrint */

#define WPP_INIT_TRACING(DriverObject, RegistryPath)  ((void)0)
#define WPP_CLEANUP(DriverObject)                     ((void)0)

/* ETW trace levels (must be defined for TraceEvents fallback) */
#ifndef TRACE_LEVEL_CRITICAL
#define TRACE_LEVEL_CRITICAL    1
#define TRACE_LEVEL_ERROR       2
#define TRACE_LEVEL_WARNING     3
#define TRACE_LEVEL_INFORMATION 4
#define TRACE_LEVEL_VERBOSE     5
#endif

/* Our level aliases */
#define CYPORT_LEVEL_CRITICAL   TRACE_LEVEL_CRITICAL
#define CYPORT_LEVEL_ERROR      TRACE_LEVEL_ERROR
#define CYPORT_LEVEL_WARNING    TRACE_LEVEL_WARNING
#define CYPORT_LEVEL_INFO       TRACE_LEVEL_INFORMATION
#define CYPORT_LEVEL_VERBOSE    TRACE_LEVEL_VERBOSE

/* Trace flag constants — map to bit positions in the control GUID.
 * These are used as the second argument to TraceEvents. In non-WPP
 * builds they're ignored (the DbgPrint fallback only uses level). */
#define CYPORT_INIT     0x001
#define CYPORT_PNP      0x002
#define CYPORT_POWER    0x004
#define CYPORT_IOCTL    0x008
#define CYPORT_READ     0x010
#define CYPORT_WRITE    0x020
#define CYPORT_ISR      0x040
#define CYPORT_HW       0x080
#define CYPORT_FLOW     0x100
#define CYPORT_MODEM    0x200

/* Map TraceEvents to our DbgPrint macros */
#define TraceEvents(level, flag, fmt, ...)                             \
    do {                                                               \
        if ((level) <= 2)      CyError(fmt "\n", ##__VA_ARGS__);        \
        else if ((level) <= 3) CyWarn(fmt "\n", ##__VA_ARGS__);         \
        else if ((level) <= 4) CyInfo(fmt "\n", ##__VA_ARGS__);         \
        else                   CyVerbose(fmt "\n", ##__VA_ARGS__);      \
    } while (0)

#endif /* WPP_ENABLED */


/* ====================================================================
 * FUNCTION ENTRY/EXIT TRACING
 * ====================================================================
 * These macros generate entry/exit traces with consistent formatting.
 * The function name is automatically captured via __FUNCTION__.
 *
 * Usage:
 *   NTSTATUS CyCreate(PDEVICE_OBJECT DevObj, PIRP Irp)
 *   {
 *       CY_FUNC_ENTER();
 *       ...
 *       CY_FUNC_EXIT(status);
 *   }
 * ==================================================================== */

#define CY_FUNC_ENTER()                                                \
    TraceEvents(CYPORT_LEVEL_VERBOSE, CYPORT_INIT,                     \
                "--> %s", __FUNCTION__)

#define CY_FUNC_EXIT(status)                                           \
    TraceEvents(CYPORT_LEVEL_VERBOSE, CYPORT_INIT,                     \
                "<-- %s: 0x%08X", __FUNCTION__, (ULONG)(status))

#define CY_FUNC_EXIT_VOID()                                           \
    TraceEvents(CYPORT_LEVEL_VERBOSE, CYPORT_INIT,                     \
                "<-- %s", __FUNCTION__)


/* ====================================================================
 * IRP TRACING
 * ====================================================================
 * Trace every IRP received with major/minor function codes.
 * ==================================================================== */

#define CY_TRACE_IRP(irp, major, minor)                                \
    TraceEvents(CYPORT_LEVEL_INFO, CYPORT_IOCTL,                      \
                "IRP %p: MJ=%d MN=%d",                                 \
                (irp), (int)(major), (int)(minor))

#define CY_TRACE_IOCTL(irp, code)                                      \
    TraceEvents(CYPORT_LEVEL_INFO, CYPORT_IOCTL,                      \
                "IRP %p: IOCTL 0x%08X", (irp), (ULONG)(code))


#endif /* CYTRACE_H */
