ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³                       QFront registration order form                       ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

  QFront is a  commercially sold  product.  For this  reason, you may only run
the software free-of-charge during  the 45 day  evaluation period.  After this
period, you  must register  the software or discontinue its use.  Registration
entitles you to a  non-expiring  keyfile and unlimited support via the support
BBS.
  Each  QFront registration is  valid for use on a single  CPU or on a  single
BBS system (multi-node systems require only a single registration).
  Registrations may be paid in U.S. funds only.
  There are two methods of registering QFront - by  placing your order  online
with the support BBS using your Visa/Mastercard, or by filling out and mailing
this registration form. We suggest that you place your order online   whenever
possible as this will allow you to obtain your keyfile much more quickly.  The
support BBS phone number is 906-482-8376.
  The  preferred  method  of payment  is  by credit  card.  Cards accepted are
Visa and MasterCard.
  Personal  checks are also accepted, but must be  cleared  by our bank before
registration  is granted.  Therefore, it is faster  to  use  a money  order if
possible.
  After mailing  this registration form (and allowing  adequate time for  mail
and processing of your order), you can  call the  support  BBS at 906-482-8376
and enter the KEY door to obtain your new keyfile.


  NOTICE!!!  If you are  paying by check, the  check must be  in US FUNDS!  If
your check is NOT in US funds, your registration will not be processed.


ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³                                 Invoice                                    ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ


          QFront Registration ........................... $84.95
          (Includes the user license and a serialized key file)


          Add 6% Michigan sales tax if applicable ....... $________


                                                    TOTAL $________


     If paying by credit card:

       Card number      ____________________________________________

       Expiration date  ____________

       Cardholder name  ____________________________________________

       Signature        ____________________________________________


     Remit to:

       Rob Kittredge
       c/o QFront Registration
       13580 Leonard
       Nunica, MI 49448  USA

ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
³                     Required Registration Information                      ³
ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

     Name      _________________________________________________________

     Company   _________________________________________________________

     Address   _________________________________________________________

               _________________________________________________________

     City      _________________________________________________________

     State     _________________________________________________________

     Zipcode   _____________

     Country   _________________________________________________________

     Phone     BBS  ______________________  Voice  _____________________

     BBS name  _________________________________________________________

     Number
     of nodes  _______

     BBS type  PCBoard _____    Wildcat! _____

     Comments  _________________________________________________________

     Comments  _________________________________________________________

     Comments  _________________________________________________________

     Comments  _________________________________________________________


                           THANK YOU FOR YOUR ORDER!

