/* ====================================================================
 * cylog.c — Event Log Integration
 * ====================================================================
 * Provides wrapper functions for writing entries to the Windows
 * Event Log via IoAllocateErrorLogEntry + IoWriteErrorLogEntry.
 *
 * These functions are called from throughout the driver when
 * significant events occur:
 *   - Driver loaded/unloaded
 *   - Port opened/closed
 *   - Hardware errors (overrun, parity, framing)
 *   - Hardware failures (no chips, memory map failed)
 *   - Power state changes
 *
 * The messages are defined in cylog.mc and compiled by mc.exe into
 * cylog.h (which we include for the CYLOG_* message ID constants).
 * The message text is embedded in cyport.sys as a resource table,
 * so Event Viewer can display human-readable descriptions.
 *
 * Event Log entries consist of:
 *   1. An IO_ERROR_LOG_PACKET with the error code (message ID)
 *   2. Optional DumpData (ULONG array for numeric values)
 *   3. Optional insertion strings (for %1, %2 etc. in the message)
 *
 * Why event logging matters:
 *   - DbgPrint/CyDbgPrint only works in checked builds or with
 *     a kernel debugger attached. Event Log works on production
 *     systems with no debugger.
 *   - System administrators can monitor Event Viewer for hardware
 *     errors without running debug tools.
 *   - When a customer reports "my serial port stopped working",
 *     the Event Log tells us exactly what happened.
 *
 * Sources:
 *   - Original cyyport.sys imports: IoAllocateErrorLogEntry,
 *     IoWriteErrorLogEntry (confirmed by import analysis)
 *   - WDK serial sample (serial\sys\log.c)
 *   - MSDN IoWriteErrorLogEntry documentation
 *
 * License: GPLv3
 * ====================================================================
 */

#include "cycommon.h"

#ifdef WPP_ENABLED
#include "cylog.tmh"
#endif

/* Include the message ID constants generated by mc.exe.
 * These are #defines like CYLOG_DRIVER_LOADED, CYLOG_BUFFER_OVERRUN,
 * etc. that correspond to the message text in cylog.mc.
 *
 * NOTE: cylog.h is GENERATED by "mc cylog.mc". It does not exist
 * until the message compiler runs. If building without mc.exe,
 * define the constants manually below as a fallback. */
#ifdef CYLOG_H_GENERATED
#include "cylog.h"
#else
/* Fallback definitions if cylog.h hasn't been generated yet.
 * These MUST match the MessageId values in cylog.mc.
 * Severity and Facility bits are encoded in the high word:
 *   Bits 31:30 = Severity (0=Success, 1=Info, 2=Warning, 3=Error)
 *   Bits 27:16 = Facility (0x100 = Cyclades)
 *   Bits 15:0  = MessageId */
#define CYLOG_DRIVER_LOADED             ((NTSTATUS)0x41000001L)
#define CYLOG_PORT_OPENED               ((NTSTATUS)0x41000002L)
#define CYLOG_PORT_CLOSED               ((NTSTATUS)0x41000003L)
#define CYLOG_POWER_SUSPEND             ((NTSTATUS)0x41000004L)
#define CYLOG_POWER_RESUME              ((NTSTATUS)0x41000005L)
#define CYLOG_DRIVER_UNLOADED           ((NTSTATUS)0x41000006L)
#define CYLOG_BUFFER_OVERRUN            ((NTSTATUS)0x81000100L)
#define CYLOG_FIFO_OVERRUN              ((NTSTATUS)0x81000101L)
#define CYLOG_PARITY_ERRORS             ((NTSTATUS)0x81000102L)
#define CYLOG_FRAMING_ERRORS            ((NTSTATUS)0x81000103L)
#define CYLOG_BREAK_RECEIVED            ((NTSTATUS)0x81000104L)
#define CYLOG_ISR_STUCK                 ((NTSTATUS)0x81000105L)
#define CYLOG_NO_CHIPS_FOUND            ((NTSTATUS)0xC1000200L)
#define CYLOG_MEMORY_MAP_FAILED         ((NTSTATUS)0xC1000201L)
#define CYLOG_INTERRUPT_CONNECT_FAILED  ((NTSTATUS)0xC1000202L)
#define CYLOG_PDO_CREATE_FAILED         ((NTSTATUS)0xC1000203L)
#define CYLOG_EOSRR_MISSED              ((NTSTATUS)0xC1000204L)
#define CYLOG_POWER_RESTORE_FAILED      ((NTSTATUS)0xC1000205L)
#endif


/* ====================================================================
 * CyLogEvent — Write an event log entry
 * ====================================================================
 * Core function that all other CyLogXxx functions call.
 *
 * Parameters:
 *   DevObj      — device object to associate with the event
 *   ErrorCode   — CYLOG_* message ID constant
 *   UniqueId    — unique sequence number (helps correlate with debug)
 *   DumpData    — array of ULONG values for numeric insertion
 *   DumpCount   — number of ULONGs in DumpData (0 if none)
 *   NtStatus    — NTSTATUS to record (STATUS_SUCCESS if none)
 *
 * The function allocates an IO_ERROR_LOG_PACKET, fills it with the
 * event data, and hands it to IoWriteErrorLogEntry. After that call,
 * the I/O manager OWNS the packet — we must NOT free it.
 *
 * IoAllocateErrorLogEntry can fail (returns NULL) if the system is
 * low on memory. We silently drop the event in that case — losing
 * a log entry is better than crashing. The CyDbgPrint output is
 * our backup for debug builds.
 * ==================================================================== */

VOID CyLogEvent(
    PDEVICE_OBJECT  DevObj,
    NTSTATUS        ErrorCode,
    ULONG           UniqueId,
    PULONG          DumpData,
    ULONG           DumpCount,
    NTSTATUS        NtStatus)
{
    PIO_ERROR_LOG_PACKET logEntry;
    UCHAR                packetSize;

    /* Calculate packet size.
     * IO_ERROR_LOG_PACKET has room for the fixed fields.
     * DumpData is appended after the fixed fields.
     * Maximum packet size is ERROR_LOG_MAXIMUM_SIZE (about 150 bytes).
     * Each ULONG in DumpData takes 4 bytes. */
    packetSize = sizeof(IO_ERROR_LOG_PACKET) +
                 (UCHAR)(DumpCount * sizeof(ULONG));

    /* Cap at maximum size — if we exceed it, truncate DumpData.
     * This prevents IoAllocateErrorLogEntry from failing due to
     * an oversized request. */
    if (packetSize > ERROR_LOG_MAXIMUM_SIZE) {
        packetSize = ERROR_LOG_MAXIMUM_SIZE;
        DumpCount = (ERROR_LOG_MAXIMUM_SIZE - sizeof(IO_ERROR_LOG_PACKET))
                    / sizeof(ULONG);
    }

    /* Allocate the log entry from the system's error log pool.
     * This is a fixed-size non-paged pool allocation. The system
     * queues it for the Event Log service to pick up. */
    logEntry = (PIO_ERROR_LOG_PACKET)IoAllocateErrorLogEntry(
        DevObj, packetSize);

    if (!logEntry) {
        /* System is low on memory — can't log this event.
         * Fall through to CyDbgPrint below for debug builds. */
        CyWarn("EVENT LOG: failed to allocate log entry "
               "(ErrorCode=0x%08X)\n", ErrorCode);
        return;
    }

    /* Fill in the packet fields */
    logEntry->ErrorCode         = ErrorCode;
    logEntry->SequenceNumber    = 0;
    logEntry->MajorFunctionCode = 0;
    logEntry->RetryCount        = 0;
    logEntry->UniqueErrorValue  = UniqueId;
    logEntry->FinalStatus       = NtStatus;
    logEntry->DumpDataSize      = (USHORT)(DumpCount * sizeof(ULONG));

    /* Copy numeric dump data (if any).
     * These appear in Event Viewer as "Data:" hex values.
     * They're useful for recording register values, port numbers,
     * error counts — anything numeric that helps diagnose issues. */
    if (DumpCount > 0 && DumpData != NULL) {
        ULONG i;
        for (i = 0; i < DumpCount; i++) {
            logEntry->DumpData[i] = DumpData[i];
        }
    }

    /* Hand the packet to the I/O manager.
     * CRITICAL: After this call, we do NOT own the packet anymore.
     * The I/O manager queues it for the Event Log service.
     * Do NOT call ExFreePool on it — the system frees it after
     * the Event Log service has written it to disk. */
    IoWriteErrorLogEntry(logEntry);

    /* Also emit a debug print so the event is visible in
     * checked builds without needing to check Event Viewer */
    CyTrace("EVENT LOG: code=0x%08X unique=%lu status=0x%08X "
            "dumpCount=%lu\n",
            ErrorCode, UniqueId, NtStatus, DumpCount);
}


/* ====================================================================
 * Convenience Functions — Typed wrappers for common events
 * ====================================================================
 * Each function logs a specific event with the right message ID
 * and dump data format. These are called from throughout the driver
 * at the appropriate points.
 * ==================================================================== */


/* ---- Driver lifecycle ---- */

VOID CyLogDriverLoaded(
    PDEVICE_OBJECT  DevObj,
    ULONG           NumChips,
    ULONG           NumPorts)
{
    ULONG data[2];
    data[0] = NumChips;
    data[1] = NumPorts;

    CyLogEvent(DevObj, CYLOG_DRIVER_LOADED, 0, data, 2, STATUS_SUCCESS);

    CyInfo("EVENT: Driver loaded — %lu chip(s), %lu port(s)\n",
           NumChips, NumPorts);
}

VOID CyLogDriverUnloaded(PDEVICE_OBJECT DevObj)
{
    CyLogEvent(DevObj, CYLOG_DRIVER_UNLOADED, 0, NULL, 0, STATUS_SUCCESS);

    CyInfo("EVENT: Driver unloaded\n");
}


/* ---- Port lifecycle ---- */

VOID CyLogPortOpened(
    PDEVICE_OBJECT  DevObj,
    ULONG           PortIndex,
    ULONG           ComNumber,
    ULONG           BaudRate)
{
    ULONG data[3];
    data[0] = PortIndex;
    data[1] = ComNumber;
    data[2] = BaudRate;

    CyLogEvent(DevObj, CYLOG_PORT_OPENED, PortIndex,
               data, 3, STATUS_SUCCESS);

    CyInfo("EVENT: Port %lu (COM%lu) opened at %lu baud\n",
           PortIndex, ComNumber, BaudRate);
}

VOID CyLogPortClosed(
    PDEVICE_OBJECT  DevObj,
    ULONG           PortIndex,
    ULONG           ComNumber,
    ULONG           TxTotal,
    ULONG           RxTotal)
{
    ULONG data[4];
    data[0] = PortIndex;
    data[1] = ComNumber;
    data[2] = TxTotal;
    data[3] = RxTotal;

    CyLogEvent(DevObj, CYLOG_PORT_CLOSED, PortIndex,
               data, 4, STATUS_SUCCESS);

    CyInfo("EVENT: Port %lu (COM%lu) closed — TX=%lu RX=%lu bytes\n",
           PortIndex, ComNumber, TxTotal, RxTotal);
}


/* ---- Hardware errors ---- */

VOID CyLogBufferOverrun(
    PDEVICE_OBJECT  DevObj,
    ULONG           PortIndex,
    ULONG           BytesLost)
{
    ULONG data[2];
    data[0] = PortIndex;
    data[1] = BytesLost;

    CyLogEvent(DevObj, CYLOG_BUFFER_OVERRUN, PortIndex,
               data, 2, STATUS_DATA_OVERRUN);

    CyWarn("EVENT: Port %lu buffer overrun — %lu bytes lost\n",
           PortIndex, BytesLost);
}

VOID CyLogFifoOverrun(
    PDEVICE_OBJECT  DevObj,
    ULONG           PortIndex)
{
    ULONG data[1];
    data[0] = PortIndex;

    CyLogEvent(DevObj, CYLOG_FIFO_OVERRUN, PortIndex,
               data, 1, STATUS_DATA_OVERRUN);

    CyWarn("EVENT: Port %lu hardware FIFO overrun\n", PortIndex);
}

VOID CyLogParityErrors(
    PDEVICE_OBJECT  DevObj,
    ULONG           PortIndex,
    ULONG           ErrorCount)
{
    ULONG data[2];
    data[0] = PortIndex;
    data[1] = ErrorCount;

    CyLogEvent(DevObj, CYLOG_PARITY_ERRORS, PortIndex,
               data, 2, STATUS_SUCCESS);

    CyWarn("EVENT: Port %lu — %lu parity error(s)\n",
           PortIndex, ErrorCount);
}

VOID CyLogFramingErrors(
    PDEVICE_OBJECT  DevObj,
    ULONG           PortIndex,
    ULONG           ErrorCount)
{
    ULONG data[2];
    data[0] = PortIndex;
    data[1] = ErrorCount;

    CyLogEvent(DevObj, CYLOG_FRAMING_ERRORS, PortIndex,
               data, 2, STATUS_SUCCESS);

    CyWarn("EVENT: Port %lu — %lu framing error(s)\n",
           PortIndex, ErrorCount);
}


/* ---- Hardware failures (critical) ---- */

VOID CyLogNoChipsFound(
    PDEVICE_OBJECT  DevObj,
    PHYSICAL_ADDRESS MemAddress)
{
    ULONG data[2];
    data[0] = MemAddress.LowPart;
    data[1] = MemAddress.HighPart;

    CyLogEvent(DevObj, CYLOG_NO_CHIPS_FOUND, 0,
               data, 2, STATUS_DEVICE_DOES_NOT_EXIST);

    CyError("EVENT: No CD1400 chips found at 0x%08X%08X\n",
            MemAddress.HighPart, MemAddress.LowPart);
}

VOID CyLogMemoryMapFailed(
    PDEVICE_OBJECT  DevObj,
    PHYSICAL_ADDRESS MemAddress,
    ULONG           Length)
{
    ULONG data[3];
    data[0] = MemAddress.LowPart;
    data[1] = MemAddress.HighPart;
    data[2] = Length;

    CyLogEvent(DevObj, CYLOG_MEMORY_MAP_FAILED, 0,
               data, 3, STATUS_INSUFFICIENT_RESOURCES);

    CyError("EVENT: MmMapIoSpace failed at 0x%08X%08X (%lu bytes)\n",
            MemAddress.HighPart, MemAddress.LowPart, Length);
}

VOID CyLogInterruptConnectFailed(
    PDEVICE_OBJECT  DevObj,
    NTSTATUS        NtStatus)
{
    ULONG data[1];
    data[0] = (ULONG)NtStatus;

    CyLogEvent(DevObj, CYLOG_INTERRUPT_CONNECT_FAILED, 0,
               data, 1, NtStatus);

    CyError("EVENT: IoConnectInterrupt failed: 0x%08X\n", NtStatus);
}


/* ---- Power management ---- */

VOID CyLogPowerSuspend(
    PDEVICE_OBJECT  DevObj,
    ULONG           PortIndex)
{
    ULONG data[1];
    data[0] = PortIndex;

    CyLogEvent(DevObj, CYLOG_POWER_SUSPEND, PortIndex,
               data, 1, STATUS_SUCCESS);

    CyInfo("EVENT: Port %lu suspending (D0→D3)\n", PortIndex);
}

VOID CyLogPowerResume(
    PDEVICE_OBJECT  DevObj,
    ULONG           PortIndex)
{
    ULONG data[1];
    data[0] = PortIndex;

    CyLogEvent(DevObj, CYLOG_POWER_RESUME, PortIndex,
               data, 1, STATUS_SUCCESS);

    CyInfo("EVENT: Port %lu resuming (D3→D0)\n", PortIndex);
}
