/o- \proj\pcb\obj\bc50\noscroll.obj+
/o- \proj\lib\bcdos\bc50\misc\large\swap.obj+
/o- \proj\pcb\obj\bc50\pcboard.obj+
/o- \proj\pcb\obj\bc50\overlay.obj+
/o- \proj\pcb\obj\bc50\inkey.obj+
/o- \proj\pcb\obj\bc50\memory.obj+
/o- \proj\pcb\obj\bc50\modem.obj+
/o- \proj\pcb\obj\bc50\dosopen.obj+
/o- \proj\pcb\obj\bc50\dosclose.obj+
/o- \proj\pcb\obj\bc50\dosread.obj+
/o- \proj\pcb\obj\bc50\doswrite.obj+
/o- \proj\pcb\obj\bc50\dostime.obj+
/o- \proj\pcb\obj\bc50\ansi.obj+
/o- \proj\pcb\obj\bc50\async.obj+
/o- \proj\pcb\obj\bc50\bgkey.obj+
/o- \proj\pcb\obj\bc50\cutil.obj+
/o- \proj\pcb\obj\bc50\memmove.obj+
/o- \proj\pcb\obj\bc50\timer.obj+
/o- \proj\pcb\obj\bc50\display.obj+
/o- \proj\pcb\obj\bc50\xlate.obj+
/o- \proj\pcb\obj\bc50\devioctl.obj+
/o- \proj\pcb\obj\bc50\VAR.obj+
/o- \proj\pcb\obj\bc50\ticdelay.obj+
/o- \proj\pcb\obj\bc50\nonovrly.obj+
/o+ \proj\pcb\obj\bc50\init.obj+
/o+ \proj\pcb\obj\bc50\pcbtext.obj+
/o+ \proj\pcb\obj\bc50\language.obj+
/o+ \proj\pcb\obj\bc50\sys.obj+
/o+ \proj\pcb\obj\bc50\log.obj+
/o+ \proj\pcb\obj\bc50\token.obj+
/o+ \proj\pcb\obj\bc50\users.obj+
/o+ \proj\pcb\obj\bc50\usernet.obj+
/o+ \proj\pcb\obj\bc50\stats.obj+
/o+ \proj\pcb\obj\bc50\screen.obj+
/o+ \proj\pcb\obj\bc50\callwait.obj+
/o+ \proj\pcb\obj\bc50\account.obj+
/o+ \proj\pcb\obj\bc50\blt.obj+
/o+ \proj\pcb\obj\bc50\capture.obj+
/o+ \proj\pcb\obj\bc50\chat.obj+
/o+ \proj\pcb\obj\bc50\cmds.obj+
/o+ \proj\pcb\obj\bc50\command.obj+
/o+ \proj\pcb\obj\bc50\crc32.obj+
/o+ \proj\pcb\obj\bc50\confrnce.obj+
/o+ \proj\pcb\obj\bc50\copyfile.obj+
/o+ \proj\pcb\obj\bc50\dir.obj+
/o+ \proj\pcb\obj\bc50\diz.obj+
/o+ \proj\pcb\obj\bc50\dlpath.obj+
/o+ \proj\pcb\obj\bc50\doors.obj+
/o+ \proj\pcb\obj\bc50\event.obj+
/o+ \proj\pcb\obj\bc50\data.obj+
/o+ \proj\pcb\obj\bc50\passthru.obj+
/o+ \proj\pcb\obj\bc50\fidomenu.obj+
/o+ \proj\pcb\obj\bc50\fidomisc.obj+
/o+ \proj\pcb\obj\bc50\filelist.obj+
/o+ \proj\pcb\obj\bc50\files.obj+
/o+ \proj\pcb\obj\bc50\help.obj+
/o+ \proj\pcb\obj\bc50\index.obj+
/o+ \proj\pcb\obj\bc50\input.obj+
/o+ \proj\pcb\obj\bc50\logview.obj+
/o+ \proj\pcb\obj\bc50\login.obj+
/o+ \proj\pcb\obj\bc50\msgbase.obj+
/o+ \proj\pcb\obj\bc50\messages.obj+
/o+ \proj\pcb\obj\bc50\misc.obj+
/o+ \proj\pcb\obj\bc50\modemasy.obj+
/o+ \proj\pcb\obj\bc50\modemfos.obj+
/o+ \proj\pcb\obj\bc50\modemdrv.obj+
/o+ \proj\pcb\obj\bc50\modemos2.obj+
/o+ \proj\pcb\obj\bc50\msgenter.obj+
/o+ \proj\pcb\obj\bc50\msgread.obj+
/o+ \proj\pcb\obj\bc50\msgscan.obj+
/o+ \proj\pcb\obj\bc50\newchat.obj+
/o+ \proj\pcb\obj\bc50\node.obj+
/o+ \proj\pcb\obj\bc50\pcbtoss.obj+
/o+ \proj\pcb\obj\bc50\tossmisc.obj+
/o+ \proj\pcb\obj\bc50\ratio.obj+
/o+ \proj\pcb\obj\bc50\recycle.obj+
/o+ \proj\pcb\obj\bc50\script.obj+
/o+ \proj\pcb\obj\bc50\scrlback.obj+
/o+ \proj\pcb\obj\bc50\settings.obj+
/o+ \proj\pcb\obj\bc50\shell.obj+
/o+ \proj\pcb\obj\bc50\showerr.obj+
/o+ \proj\pcb\obj\bc50\status.obj+
/o+ \proj\pcb\obj\bc50\transfer.obj+
/o+ \proj\pcb\obj\bc50\userstat.obj+
/o+ \proj\pcb\obj\bc50\usersys.obj+
/o+ \proj\pcb\obj\bc50\userscan.obj+
/o+ \proj\pcb\obj\bc50\usrmaint.obj+
/o+ \proj\pcb\obj\bc50\FILESTUB.obj+
/o+ \proj\pcb\obj\bc50\LABEL.obj+
/o+ \proj\pcb\obj\bc50\SCRMISC.obj+
/o+ \proj\pcb\obj\bc50\NEWSCR.obj+
/o+ \proj\pcb\obj\bc50\PCBMISC.obj+
/o+ \proj\pcb\obj\bc50\SCREXEC.obj+
/o+ \proj\pcb\obj\bc50\EVALP.obj+
/o+ \proj\pcb\obj\bc50\EXECDB.obj+
/o+ \proj\pcb\obj\bc50\MENU.obj+
/o+ \proj\pcb\obj\bc50\LRAND.obj+
/o+ \proj\pcb\obj\bc50\DBASE.obj+
/o+ \proj\pcb\obj\bc50\recemsi.obj+
/o+ \proj\pcb\obj\bc50\fconfig.obj+
/o+ \proj\pcb\obj\bc50\hex.obj+
/o+ \proj\pcb\obj\bc50\crc-16f.obj+
/o+ \proj\pcb\obj\bc50\xmitemsi.obj+
/o+ \proj\pcb\obj\bc50\fidofunc.obj+
/o+ \proj\pcb\obj\bc50\recwazoo.obj+
/o+ \proj\pcb\obj\bc50\umwf.obj+
/o+ \proj\pcb\obj\bc50\pcbmsgs.obj+
/o- \proj\pcb\obj\bc50\msgstub.obj+
/o+ \proj\pcb\obj\bc50\fidoque.obj+
/o+ \proj\pcb\obj\bc50\fidomsg.obj+
/o+ \proj\pcb\obj\bc50\seenby.obj+
/o+ \proj\pcb\obj\bc50\dupechec.obj+
/o+ \proj\lib\bcdos\bc50\misc\large\bmsearch.obj+
/o+ \proj\lib\bcdos\bc50\misc\large\psearch.obj+
/o+ \proj\lib\bcdos\bc50\misc\large\julian.obj+
/o+ \proj\lib\bcdos\bc50\misc\large\ctod.obj+
/o+ \proj\lib\bcdos\bc50\misc\large\append.obj+
/o+ \proj\lib\bcdos\bc50\misc\large\proper.obj+
/o+ \proj\lib\bcdos\bc50\misc\large\diskfree.obj+
/o+ \proj\lib\bcdos\bc50\misc\large\subst.obj+
/o+ \proj\lib\bcdos\bc50\dos\large\doserror.obj+
/o+ \proj\lib\bcdos\bc50\dos\large\dosfread.obj+
/o+ \proj\lib\bcdos\bc50\dos\large\dosfgets.obj+
/o+ \proj\lib\bcdos\bc50\dos\large\dosfugts.obj+
/o+ \proj\lib\bcdos\bc50\pcb\large\datafil2.obj+
/o+ \proj\lib\bcdos\bc50\pcb\large\cnames.obj+
/o+ \proj\lib\bcdos\bc50\country\large\country.obj+
/o+ \proj\lib\bcdos\bc50\screen\large\getmode.obj+
/o+ \proj\lib\bcdos\bc50\screen\large\box.obj
