/* ====================================================================
 * cyenum.c — Bus Enumerator (FDO side)
 * ====================================================================
 * Handles DriverEntry, AddDevice, and FDO PnP IRPs.
 *
 * The bus enumerator is responsible for:
 *   1. Detecting CD1400 chips on the Cyclom-Y card
 *   2. Creating a child PDO for each serial port (chip × channel)
 *   3. Reporting children via IRP_MN_QUERY_DEVICE_RELATIONS
 *   4. Managing the card's memory-mapped window lifetime
 *
 * The bus enumerator does NOT handle serial I/O — that's the PDO's
 * job. The bus enumerator does NOT connect interrupts
 * — that's also the PDO's job. This matches the original cyclom-y.sys
 * which imports IoConnectInterrupt nowhere (only cyyport.sys does).
 *
 * Architecture reference:
 *   - Microsoft serenum sample (WDK serial/serenum/)
 *   - A2_A3_ARCHITECTURE.md research document
 *   - Original cyclom-y.sys import analysis (47 ntoskrnl imports)
 *
 * License: GPLv3
 * ====================================================================
 */

#include "cycommon.h"

/* WPP tracing: include the trace message header generated by the
 * WPP preprocessor. When building with the WDK, the build system
 * runs tracewpp.exe on this .c file and generates cyenum.tmh.
 * When cross-compiling with OW, WPP_ENABLED is not defined and
 * this include is skipped — we fall back to DbgPrint. */
#ifdef WPP_ENABLED
#include "cyenum.tmh"
#endif

/* ====================================================================
 * Global Debug Level
 * ====================================================================
 * Runtime debug level — controls which CyDbgPrint calls produce
 * output. Referenced by CyDbgPrint macro in cydebug.h.
 *
 * Checked (debug) build:  default = CYPORT_INFO (3)
 * Free (release) build:   default = CYPORT_ERROR (1)
 *
 * Can be overridden at load time via registry:
 *   HKLM\SYSTEM\CurrentControlSet\Services\cyport\Parameters
 *     DebugLevel : REG_DWORD : 0-5
 * ==================================================================== */

#if DBG
ULONG g_CyDebugLevel = CYPORT_INFO;    /* Debug build: show info+    */
#else
ULONG g_CyDebugLevel = CYPORT_ERROR;   /* Release build: errors only */
#endif

/* PCI vs ISA register shift — set during START_DEVICE resource
 * parsing. Used by CyReadReg/CyWriteReg inline functions in
 * cycommon.h. 0 = ISA (no shift), 1 = PCI (shift reg × 2).
 * (Fix for known issue 5.1) */
ULONG g_CyBusIndex = 0;

/* ====================================================================
 * Pageable Code Sections
 * ====================================================================
 * These pragmas tell the linker which code can be paged out.
 * INIT section is discarded after DriverEntry returns.
 * PAGE section is pageable (not called at DISPATCH_LEVEL or above).
 * Non-decorated code stays in non-paged pool (safe for ISR/DPC).
 * ==================================================================== */

#ifdef ALLOC_PRAGMA
#pragma alloc_text(INIT, DriverEntry)
#pragma alloc_text(PAGE, CyAddDevice)
#pragma alloc_text(PAGE, CyFdoPnP)
#pragma alloc_text(PAGE, CyDispatchPnP)
#endif


/* ====================================================================
 * Completion Routine for Forward-First Pattern
 * ====================================================================
 * IRP_MN_START_DEVICE must be forwarded to the lower driver first.
 * We set this as the completion routine, which signals an event
 * when the lower driver completes the IRP. Then our code runs
 * AFTER the lower driver has started successfully.
 *
 * This is MANDATORY for WDM bus drivers. If we touch hardware
 * before the lower driver (PCI bus driver) has mapped our resources,
 * we'll access invalid memory.
 *
 * Pattern confirmed in serenum/pnp.c: SerenumSyncCompletion.
 * ==================================================================== */

static NTSTATUS NTAPI CySyncCompletion(
    PDEVICE_OBJECT  DevObj,
    PIRP            Irp,
    PVOID           Context)
{
    UNREFERENCED_PARAMETER(DevObj);
    UNREFERENCED_PARAMETER(Irp);

    /* Signal the event that our PnP handler is waiting on */
    KeSetEvent((PKEVENT)Context, IO_NO_INCREMENT, FALSE);

    /* Return STATUS_MORE_PROCESSING_REQUIRED to prevent the I/O
     * manager from completing the IRP. We'll complete it ourselves
     * after doing our post-start work. */
    return STATUS_MORE_PROCESSING_REQUIRED;
}


/* ====================================================================
 * CyScanForChips — Detect CD1400 chips in the memory window
 * ====================================================================
 * Scans the mapped card memory for CD1400 chips by reading the
 * Global Firmware Revision Code Register (GFRCR) at each 0x400
 * offset. Valid revisions are 0x46 (Rev G, 25 MHz) and 0x48
 * (Rev J, 60 MHz).
 *
 * Returns the number of chips found (0 = no hardware).
 * ==================================================================== */

static ULONG CyScanForChips(PCY_FDO_EXT fdoExt)
{
    ULONG chip;
    UCHAR rev;

    fdoExt->NumChips = 0;

    for (chip = 0; chip < CY_MAX_CHIPS; chip++) {
        PUCHAR chipBase = fdoExt->CardBase + (chip * CY_REG_SIZE);

        /* Read the Global Firmware Revision Code Register.
         * Valid CD1400: Rev G (0x46) or Rev J (0x48).
         * The original cyclom-y.sys uses READ_REGISTER_UCHAR for this. */
        rev = CyReadReg(chipBase, CyGFRCR);

        if (rev != CD1400_REV_G && rev != CD1400_REV_J) {
            /* Not a recognized CD1400 — stop scanning.
             * We don't accept the 0x40-0x4F range anymore
             * (audit warning W5: too permissive). */
            break;
        }

        fdoExt->Chips[chip].Base     = chipBase;
        fdoExt->Chips[chip].Revision = rev;
        fdoExt->Chips[chip].Is60MHz  = (rev == CD1400_REV_J);
        fdoExt->NumChips++;

        CyInfo("Chip %lu at offset 0x%04X, rev 0x%02X (%s)\n",
                 chip, chip * CY_REG_SIZE, rev,
                 (rev == CD1400_REV_J) ? "60MHz" : "25MHz");
    }

    return fdoExt->NumChips;
}


/* ====================================================================
 * CyCreateChildPDOs — Create a PDO for each serial port
 * ====================================================================
 * For each detected chip × 4 channels, creates a child PDO.
 * The PDO's device extension (CY_PDO_EXT) is initialized with
 * the chip base, channel number, and back-pointer to the parent FDO.
 *
 * PDOs are unnamed — they get names when the port driver starts
 * them (IRP_MN_START_DEVICE on the PDO creates the symbolic link).
 * ==================================================================== */

static NTSTATUS CyCreateChildPDOs(PCY_FDO_EXT fdoExt)
{
    ULONG       chip, chan;
    ULONG       portIndex = 0;
    NTSTATUS    status;

    for (chip = 0; chip < fdoExt->NumChips; chip++) {
        for (chan = 0; chan < CY_PORTS_PER_CHIP; chan++) {

            PDEVICE_OBJECT  pdoObj;
            PCY_PDO_EXT     pdoExt;

            /* Create an unnamed PDO.
             * FILE_DEVICE_SERIAL_PORT tells the system this is a
             * serial port. FILE_AUTOGENERATED_DEVICE_NAME not used —
             * we'll name it when the port starts. */
            status = IoCreateDevice(
                fdoExt->Common.Self->DriverObject,
                sizeof(CY_PDO_EXT),
                NULL,                       /* Unnamed for now      */
                FILE_DEVICE_SERIAL_PORT,
                FILE_DEVICE_SECURE_OPEN,
                FALSE,                      /* Not exclusive        */
                &pdoObj);

            if (!NT_SUCCESS(status)) {
                CyError("Failed to create PDO for port %lu: "
                         "0x%08X\n", portIndex, status);
                continue;
            }

            /* ---- Zero the entire extension first ----
             * RtlZeroMemory ensures all BOOLEANs are FALSE, all
             * pointers are NULL, all counts are 0. This means we
             * only need to explicitly set fields that have non-zero
             * initial values. Any field we forget to set is safely
             * zero, not garbage from a previous allocation. */
            pdoExt = CyGetPdo(pdoObj);
            RtlZeroMemory(pdoExt, sizeof(CY_PDO_EXT));

            /* ---- Common header ----
             * IsFDO = FALSE tells CyDispatchPnP to route IRPs to
             * CyPdoPnP instead of CyFdoPnP. This is the core of
             * the dual-role single-driver architecture.
             * Self = back-pointer so any code holding the extension
             * can find the device object without a container-of macro. */
            pdoExt->Common.IsFDO     = FALSE;
            pdoExt->Common.Self      = pdoObj;
            pdoExt->Common.PnPState  = CyNotStarted;
            pdoExt->Common.SystemPowerState = PowerSystemWorking;
            pdoExt->Common.DevicePowerState = PowerDeviceD0;

            /* Remove lock: prevents the device from being deleted
             * while IRPs are still being processed. Every IRP handler
             * calls IoAcquireRemoveLock on entry and IoReleaseRemoveLock
             * on exit. The REMOVE handler calls IoReleaseRemoveLockAndWait
             * which blocks until ALL outstanding locks are released.
             * Parameters: tag for debugging, 0 = no max count, 0 = no timeout */
            IoInitializeRemoveLock(
                &pdoExt->Common.RemoveLock, CY_PDO_TAG, 0, 0);

            /* ---- Port identity ----
             * ParentFdo: back-pointer to the bus FDO. Needed so the
             * PDO can access the card's shared resources (memory map,
             * chip info) through the parent.
             * PortIndex: global port number (0-31). Used for instance ID
             * and symbolic link naming (COM3, COM4, etc.).
             * ChipIndex/Channel: identify which CD1400 and which of
             * its 4 channels this port corresponds to. */
            pdoExt->ParentFdo  = fdoExt->Common.Self;
            pdoExt->PortIndex  = portIndex;
            pdoExt->ChipIndex  = (UCHAR)chip;
            pdoExt->Channel    = (UCHAR)chan;

            /* ---- Hardware access pointers ----
             * ChipBase points into the FDO's mapped memory window
             * (CardBase + chipIndex * 0x400). The PDO does NOT own
             * this mapping — the FDO does. If the FDO unmaps the
             * memory (on REMOVE), this pointer becomes invalid.
             * We must ensure PDOs are stopped before FDO unmaps. */
            pdoExt->ChipBase   = fdoExt->Chips[chip].Base;
            pdoExt->ChipRev    = fdoExt->Chips[chip].Revision;
            pdoExt->Is60MHz    = fdoExt->Chips[chip].Is60MHz;

            /* ---- Default serial settings ----
             * 9600 8N1 is the universal default for serial ports.
             * Applications can change these via IOCTL_SERIAL_SET_*
             * after opening the port. */
            pdoExt->BaudRate   = 9600;
            pdoExt->LineControl.WordLength = 8;
            pdoExt->LineControl.StopBits   = STOP_BIT_1;
            pdoExt->LineControl.Parity     = NO_PARITY;

            /* ---- Synchronization primitives ----
             * PortLock: protects serial port state (baud, line control,
             *   modem signals) from concurrent IOCTL access.
             * ReadQueueLock / WriteQueueLock: protect the cancel-safe
             *   IRP queues. IoCsq callbacks acquire/release these.
             * EventLock: protects the WaitCommEvent IRP and event
             *   history flags from concurrent access.
             * ListHeads: doubly-linked list heads for pending IRP queues.
             *   Must be initialized before any IRP can be queued. */
            KeInitializeSpinLock(&pdoExt->PortLock);
            KeInitializeSpinLock(&pdoExt->ReadQueueLock);
            KeInitializeSpinLock(&pdoExt->WriteQueueLock);
            KeInitializeSpinLock(&pdoExt->EventLock);
            InitializeListHead(&pdoExt->ReadQueueHead);
            InitializeListHead(&pdoExt->WriteQueueHead);

            /* ---- DPCs NOT initialized here ----
             * DPCs (Deferred Procedure Calls) are the ISR's "bottom
             * half" — the ISR queues a DPC, and the DPC runs at
             * DISPATCH_LEVEL to complete pending IRPs. We can't
             * initialize them here because the DPC routines don't
             * exist yet (they're in cyisr.c). Calling KeInitializeDpc
             * with NULL as the DeferredRoutine would BSOD when the
             * DPC fires — it would jump to address 0.
             * DPCs are initialized in PDO START_DEVICE when the ISR
             * infrastructure is set up. (Audit B1 fix) */

            /* ---- Device flags ----
             * DO_BUFFERED_IO: tells the I/O manager to allocate a
             *   system buffer for read/write IRPs and copy data
             *   between user buffer and system buffer. This is
             *   required for serial ports because user buffers may
             *   be paged out when the ISR needs to access them.
             *   Without this flag, we'd need to lock user pages
             *   ourselves with MmProbeAndLockPages.
             *
             * DO_DEVICE_INITIALIZING: set by IoCreateDevice. MUST
             *   be cleared before any IRPs can be sent to us. We
             *   clear it LAST, after all initialization is done,
             *   so no IRP can arrive at a half-initialized device.
             *   Order matters: set all fields, THEN clear this flag. */
            pdoObj->Flags |= DO_BUFFERED_IO;

            /* Store in parent's child array. This must happen before
             * clearing DO_DEVICE_INITIALIZING because once that flag
             * is clear, PnP can send QUERY_DEVICE_RELATIONS and we
             * need the PDO to be in the array when we respond. */
            fdoExt->ChildPDOs[portIndex] = pdoObj;

            /* NOW it's safe to accept IRPs */
            pdoObj->Flags &= ~DO_DEVICE_INITIALIZING;

            CyInfo("Created PDO for port %lu "
                     "(chip %lu chan %lu)\n",
                     portIndex, chip, chan);

            portIndex++;
        }
    }

    fdoExt->NumPDOs = portIndex;

    CyInfo("Created %lu child PDOs\n", portIndex);
    return (portIndex > 0) ? STATUS_SUCCESS : STATUS_DEVICE_DOES_NOT_EXIST;
}


/* ====================================================================
 * DriverEntry — Driver Initialization
 * ====================================================================
 * Called once when the driver is loaded. Sets up the dispatch table.
 * Does NOT detect hardware — that happens in AddDevice + START_DEVICE.
 * This is the WDM way (not the legacy monolithic way).
 *
 * This fixes audit bug #3 (no AddDevice/PnP — monolithic style).
 * ==================================================================== */

NTSTATUS DriverEntry(
    IN PDRIVER_OBJECT   DriverObject,
    IN PUNICODE_STRING  RegistryPath)
{
    UNREFERENCED_PARAMETER(RegistryPath);

    /* Initialize WPP tracing. On WDK builds, this registers our
     * trace provider with ETW so trace controllers (tracelog,
     * TraceView) can enable our trace GUID and capture events.
     * On OW builds, this is a no-op macro. */
    WPP_INIT_TRACING(DriverObject, RegistryPath);

    CyInfo("DriverEntry\n");
    TraceEvents(CYPORT_LEVEL_INFO, CYPORT_INIT,
                "DriverEntry: Cyclades CD1400 WDM driver loading");

    /* ---- Dispatch table ----
     * The I/O manager uses this table to route IRPs to our handlers.
     * Any IRP_MJ_* code not set here gets the default handler, which
     * returns STATUS_INVALID_DEVICE_REQUEST. We set every major
     * function our driver handles.
     *
     * IMPORTANT: Both FDO and PDO share these handlers. Each handler
     * checks the IsFDO flag to determine which code path to take.
     * For PnP and Power, the routing is explicit (CyFdoPnP vs CyPdoPnP).
     * For serial I/O (Create/Close/Read/Write/IoCtl), only PDOs handle
     * them — FDO returns STATUS_INVALID_DEVICE_REQUEST. */

    /* PnP: device enumeration, start, stop, remove, power state changes.
     * This is the core of the WDM driver model. Without this, nothing works. */
    DriverObject->MajorFunction[IRP_MJ_PNP]             = CyDispatchPnP;

    /* Power: sleep/resume/hibernate. Must forward (FDO) or complete (PDO).
     * MUST call PoStartNextPowerIrp on Win2K or the power manager deadlocks. */
    DriverObject->MajorFunction[IRP_MJ_POWER]           = CyDispatchPower;

    /* Create: app calls CreateFile("COM3"). Opens the serial port. */
    DriverObject->MajorFunction[IRP_MJ_CREATE]          = CyDispatchCreate;

    /* Close: app calls CloseHandle. Releases the serial port. */
    DriverObject->MajorFunction[IRP_MJ_CLOSE]           = CyDispatchClose;

    /* Read: app calls ReadFile. Reads bytes from the serial port's RX buffer. */
    DriverObject->MajorFunction[IRP_MJ_READ]            = CyDispatchRead;

    /* Write: app calls WriteFile. Writes bytes to the serial port's TX buffer. */
    DriverObject->MajorFunction[IRP_MJ_WRITE]           = CyDispatchWrite;

    /* DeviceIoControl: app calls DeviceIoControl with IOCTL_SERIAL_*.
     * Sets baud rate, line control, modem signals, timeouts, etc. */
    DriverObject->MajorFunction[IRP_MJ_DEVICE_CONTROL]  = CyDispatchIoCtl;

    /* Cleanup: sent when the last handle to the device is closed.
     * We cancel all pending IRPs for the closing handle here.
     * This is different from Close — Cleanup fires first, then Close. */
    DriverObject->MajorFunction[IRP_MJ_CLEANUP]         = CyDispatchCleanup;

    /* ---- AddDevice callback ----
     * The PnP manager calls this when it finds a PCI device matching
     * our INF hardware IDs (VEN_120E&DEV_0101 etc.). We create our
     * FDO and attach to the device stack. We do NOT touch hardware
     * here — that happens later in IRP_MN_START_DEVICE. */
    DriverObject->DriverExtension->AddDevice = CyAddDevice;

    /* ---- No DriverUnload ----
     * WDM PnP drivers don't use DriverUnload. Device cleanup happens
     * in IRP_MN_REMOVE_DEVICE. The I/O manager unloads the driver
     * binary when no device objects remain. */

    return STATUS_SUCCESS;
}


/* ====================================================================
 * CyAddDevice — PnP AddDevice Callback
 * ====================================================================
 * Called by the PnP manager when it enumerates a PCI device matching
 * our hardware ID (VEN_120E). We create an FDO and attach it to
 * the PCI PDO's device stack.
 *
 * We do NOT touch hardware here — that happens in START_DEVICE
 * after the PCI bus driver has mapped our resources.
 * ==================================================================== */

NTSTATUS CyAddDevice(
    IN PDRIVER_OBJECT   DriverObject,
    IN PDEVICE_OBJECT   PhysicalDeviceObject)
{
    NTSTATUS        status;
    PDEVICE_OBJECT  fdoObj;
    PCY_FDO_EXT     fdoExt;

    PAGED_CODE();

    CyInfo("AddDevice (PDO=0x%p)\n", PhysicalDeviceObject);

    /* Create our FDO — unnamed, FILE_DEVICE_BUS_EXTENDER type.
     * This matches the original cyclom-y.sys which uses
     * IoCreateDevice with FILE_DEVICE_BUS_EXTENDER. */
    status = IoCreateDevice(
        DriverObject,
        sizeof(CY_FDO_EXT),
        NULL,                           /* Unnamed FDO              */
        FILE_DEVICE_BUS_EXTENDER,
        FILE_DEVICE_SECURE_OPEN,
        FALSE,                          /* Not exclusive            */
        &fdoObj);

    if (!NT_SUCCESS(status)) {
        CyError("AddDevice IoCreateDevice failed: 0x%08X\n",
                 status);
        return status;
    }

    /* ---- Zero the extension ----
     * Same pattern as PDOs: zero everything so all fields default
     * to NULL/FALSE/0. Only set non-zero fields explicitly. */
    fdoExt = CyGetFdo(fdoObj);
    RtlZeroMemory(fdoExt, sizeof(CY_FDO_EXT));

    /* ---- Common header ----
     * IsFDO = TRUE is the routing flag. When CyDispatchPnP receives
     * an IRP, it reads this flag to decide: FDO IRPs go to CyFdoPnP
     * (which forwards to lower driver), PDO IRPs go to CyPdoPnP
     * (which completes directly, no forwarding). */
    fdoExt->Common.IsFDO    = TRUE;
    fdoExt->Common.Self     = fdoObj;
    fdoExt->Common.PnPState = CyNotStarted;
    fdoExt->Common.SystemPowerState = PowerSystemWorking;
    fdoExt->Common.DevicePowerState = PowerDeviceD0;

    /* Remove lock for the FDO — same purpose as PDO remove lock.
     * Prevents device deletion while IRPs are in flight. */
    IoInitializeRemoveLock(
        &fdoExt->Common.RemoveLock, CY_POOL_TAG, 0, 0);

    /* ---- Save the PCI PDO ----
     * PhysicalDeviceObject is the PCI bus driver's PDO for our card.
     * We need this for:
     *   - IoInvalidateDeviceRelations (to trigger re-enumeration)
     *   - IoGetDeviceProperty (to query PCI resources)
     *   - PnP IRP forwarding target identification */
    fdoExt->UnderlyingPDO = PhysicalDeviceObject;

    /* ---- Enumeration lock ----
     * Protects the child PDO array (ChildPDOs[] and NumPDOs) from
     * concurrent access during BusRelations queries and device
     * removal. Although PnP IRPs are serialized per-device, a
     * re-enumeration could race with a remove on a multi-CPU system. */
    KeInitializeSpinLock(&fdoExt->EnumLock);

    /* ---- Attach to the device stack ----
     * IoAttachDeviceToDeviceStack inserts our FDO into the device
     * stack ABOVE the PCI PDO (and any lower filters). The return
     * value (LowerDevice) is the device object directly below us
     * in the stack. ALL IRPs we need to forward go to LowerDevice
     * via IoCallDriver(fdoExt->LowerDevice, Irp).
     *
     * Device stack after attach:
     *   [Our FDO]  ← top (receives IRPs from I/O manager)
     *   [PCI PDO]  ← bottom (handles PCI BAR mapping, interrupts)
     *
     * If attach fails, the PCI device is probably being removed
     * concurrently. Delete our FDO and bail. */
    fdoExt->LowerDevice = IoAttachDeviceToDeviceStack(
        fdoObj, PhysicalDeviceObject);

    if (!fdoExt->LowerDevice) {
        CyError("AddDevice IoAttachDeviceToDeviceStack failed\n");
        IoDeleteDevice(fdoObj);
        return STATUS_NO_SUCH_DEVICE;
    }

    /* ---- Match the lower device's I/O method ----
     * The lower driver (PCI bus) has already chosen buffered or direct
     * I/O. We must match it, otherwise IRPs forwarded down the stack
     * will have mismatched buffer descriptors. We copy the DO_BUFFERED_IO
     * and DO_DIRECT_IO flags from the device below us. */
    fdoObj->Flags |= fdoExt->LowerDevice->Flags &
                     (DO_BUFFERED_IO | DO_DIRECT_IO);

    /* ---- DO_POWER_PAGABLE ----
     * Tells the power manager that our power handling code can run
     * at PASSIVE_LEVEL (pageable). If we handled power at DISPATCH,
     * we'd clear this flag. Since we just forward power IRPs, we
     * can safely be pageable.
     *
     * DO_DEVICE_INITIALIZING: same as PDOs — clear LAST so no IRP
     * arrives before we're fully set up. */
    fdoObj->Flags |= DO_POWER_PAGABLE;
    fdoObj->Flags &= ~DO_DEVICE_INITIALIZING;

    CyInfo("AddDevice complete (FDO=0x%p → Lower=0x%p)\n",
             fdoObj, fdoExt->LowerDevice);

    return STATUS_SUCCESS;
}


/* ====================================================================
 * CyDispatchPnP — PnP IRP Router
 * ====================================================================
 * Routes PnP IRPs to either the FDO handler (CyFdoPnP) or the
 * PDO handler (CyPdoPnP) based on the IsFDO flag.
 *
 * Every IRP acquires the remove lock on entry. This prevents the
 * device from being removed while an IRP is being processed.
 * This fixes audit bug #8 (no remove lock on any IRP).
 * ==================================================================== */

NTSTATUS CyDispatchPnP(
    PDEVICE_OBJECT  DeviceObject,
    PIRP            Irp)
{
    PCY_COMMON_EXT  common;
    NTSTATUS        status;

    PAGED_CODE();

    common = CyGetCommon(DeviceObject);

    /* Acquire remove lock — prevents removal while IRP is active */
    status = IoAcquireRemoveLock(&common->RemoveLock, Irp);
    if (!NT_SUCCESS(status)) {
        /* Device is being removed — fail the IRP immediately */
        Irp->IoStatus.Status = status;
        Irp->IoStatus.Information = 0;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return status;
    }

    /* Route based on device type */
    if (common->IsFDO) {
        return CyFdoPnP(DeviceObject, Irp);
    } else {
        return CyPdoPnP(DeviceObject, Irp);
    }
}


/* ====================================================================
 * CyFdoPnP — FDO PnP Handler
 * ====================================================================
 * Handles PnP IRPs for the bus FDO. Key operations:
 *
 *   START_DEVICE: Forward to lower driver first (PCI maps BARs),
 *                 then map memory, scan chips, create child PDOs.
 *
 *   QUERY_DEVICE_RELATIONS (BusRelations): Return array of child
 *                 PDO pointers. ObReferenceObject each one.
 *
 *   REMOVE_DEVICE: Delete child PDOs, unmap memory, detach, delete.
 *
 * The FDO forwards most PnP IRPs to the lower device (PCI driver).
 * ==================================================================== */

NTSTATUS CyFdoPnP(PDEVICE_OBJECT DevObj, PIRP Irp)
{
    PCY_FDO_EXT         fdoExt = CyGetFdo(DevObj);
    PIO_STACK_LOCATION  irpSp  = IoGetCurrentIrpStackLocation(Irp);
    NTSTATUS            status;
    KEVENT              event;
    ULONG               i;

    PAGED_CODE();

    switch (irpSp->MinorFunction) {

    /* ================================================================
     * IRP_MN_START_DEVICE
     * ================================================================
     * Forward to lower driver first (forward-first pattern).
     * After lower driver succeeds, map our hardware and enumerate.
     * ================================================================ */
    case IRP_MN_START_DEVICE:

        CyInfo("FDO START_DEVICE\n");

        if (fdoExt->Started) {
            /* Already started — succeed */
            status = STATUS_SUCCESS;
            break;
        }

        /* Forward to lower driver and wait for completion */
        KeInitializeEvent(&event, NotificationEvent, FALSE);
        IoCopyCurrentIrpStackLocationToNext(Irp);
        IoSetCompletionRoutine(Irp, CySyncCompletion, &event,
                               TRUE, TRUE, TRUE);

        status = IoCallDriver(fdoExt->LowerDevice, Irp);

        if (status == STATUS_PENDING) {
            KeWaitForSingleObject(&event, Executive, KernelMode,
                                  FALSE, NULL);
            status = Irp->IoStatus.Status;
        }

        if (!NT_SUCCESS(status)) {
            CyError("Lower driver START failed: 0x%08X\n",
                     status);
            break;
        }

        /* Lower driver started OK — now do our initialization.
         *
         * Parse the PCI memory BAR from the resource list provided
         * by the PnP manager. The PCI bus driver has already mapped
         * the BAR to a physical address and included it in the
         * AllocatedResourcesTranslated list.
         *
         * We scan for CmResourceTypeMemory entries. The first one
         * is our CD1400 shared memory window.
         *
         * For ISA cards (no PnP resources), we fall back to the
         * default ISA memory address 0xD4000.
         * (Fix for known issue 5.5 — was hardcoded 0xD4000) */
        {
            PCM_RESOURCE_LIST           resList;
            PCM_FULL_RESOURCE_DESCRIPTOR fullDesc;
            PCM_PARTIAL_RESOURCE_LIST   partList;
            PCM_PARTIAL_RESOURCE_DESCRIPTOR partDesc;
            ULONG                       resIdx;
            BOOLEAN                     foundMemory = FALSE;
            BOOLEAN                     foundInterrupt = FALSE;

            /* Get the translated resource list from the IRP.
             * "Translated" means physical addresses are already
             * mapped by the HAL — we use these with MmMapIoSpace.
             * "Raw" resources are bus-relative and need translation. */
            resList = irpSp->Parameters.StartDevice
                          .AllocatedResourcesTranslated;

            if (resList && resList->Count > 0) {
                fullDesc = &resList->List[0];
                partList = &fullDesc->PartialResourceList;

                for (resIdx = 0; resIdx < partList->Count; resIdx++) {
                    partDesc = &partList->PartialDescriptors[resIdx];

                    switch (partDesc->Type) {

                    case CmResourceTypeMemory:
                        /* ---- Memory resource = CD1400 shared window ----
                         * The PCI BAR gives us the physical base address
                         * and length of the memory-mapped register window.
                         * We take the FIRST memory resource — it's our BAR. */
                        if (!foundMemory) {
                            fdoExt->PhysicalBase = partDesc->u.Memory.Start;
                            fdoExt->MappedLength = partDesc->u.Memory.Length;
                            foundMemory = TRUE;

                            CyInfo("PCI BAR: phys=0x%08X%08X len=%lu\n",
                                   fdoExt->PhysicalBase.HighPart,
                                   fdoExt->PhysicalBase.LowPart,
                                   fdoExt->MappedLength);

                            /* Determine if this is a PCI card (above 1MB)
                             * or ISA card (below 1MB). PCI cards use ×4
                             * register spacing, ISA uses ×2 (already in
                             * our cd1400.h offsets).
                             * (Fix for known issue 5.1) */
                            if (fdoExt->PhysicalBase.QuadPart >= 0x100000) {
                                fdoExt->BusIndex = 1;   /* PCI: shift ×2 */
                                CyInfo("Card type: PCI (BusIndex=1)\n");
                            } else {
                                fdoExt->BusIndex = 0;   /* ISA: no shift  */
                                CyInfo("Card type: ISA (BusIndex=0)\n");
                            }
                        }
                        break;

                    case CmResourceTypeInterrupt:
                        /* ---- Interrupt resource ----
                         * Save for IoConnectInterrupt later. The IRQ
                         * level, vector, and affinity come from here. */
                        if (!foundInterrupt) {
                            fdoExt->InterruptLevel =
                                (KIRQL)partDesc->u.Interrupt.Level;
                            fdoExt->InterruptVector =
                                partDesc->u.Interrupt.Vector;
                            fdoExt->InterruptAffinity =
                                partDesc->u.Interrupt.Affinity;
                            /* Latched = ISA edge-triggered,
                             * LevelSensitive = PCI level-triggered */
                            fdoExt->InterruptMode =
                                (partDesc->Flags & CM_RESOURCE_INTERRUPT_LATCHED)
                                ? Latched : LevelSensitive;
                            foundInterrupt = TRUE;

                            CyInfo("IRQ: vector=%lu level=%lu mode=%s\n",
                                   fdoExt->InterruptVector,
                                   (ULONG)fdoExt->InterruptLevel,
                                   fdoExt->InterruptMode == Latched
                                       ? "Latched(ISA)" : "Level(PCI)");
                        }
                        break;

                    default:
                        /* I/O ports, DMA, etc. — we don't use these */
                        break;
                    }
                }
            }

            /* Fall back to ISA default if no PCI resources found.
             * This handles ISA cards that don't have PnP resources
             * and are configured via "Add Hardware" wizard.
             *
             * We scan multiple common ISA memory addresses because
             * the card's DIP switches may be set to any of these.
             * Stop at the first address where a CD1400 chip responds.
             * (Phase 2: ISA multi-address scan) */
            if (!foundMemory) {
                static const ULONG isaAddresses[] = {
                    0xD0000, 0xD4000, 0xD8000, 0xDC000,
                    0xC8000, 0xCC000, 0xC0000, 0xC4000
                };
                ULONG i;
                BOOLEAN isaFound = FALSE;

                CyInfo("No PCI memory — scanning ISA addresses\n");

                for (i = 0; i < sizeof(isaAddresses)/sizeof(isaAddresses[0]); i++) {
                    PHYSICAL_ADDRESS testAddr;
                    PUCHAR testBase;

                    testAddr.QuadPart = isaAddresses[i];
                    testBase = (PUCHAR)MmMapIoSpace(
                        testAddr, CY_ISA_WINDOW, MmNonCached);

                    if (testBase) {
                        /* Try reading the GFRCR register at chip 0.
                         * Valid CD1400 revisions are 0x46 (Rev G) or
                         * 0x48 (Rev J). Anything else = no card. */
                        UCHAR rev = READ_REGISTER_UCHAR(
                            testBase + CyGFRCR);

                        if (rev == CD1400_REV_G || rev == CD1400_REV_J) {
                            CyInfo("ISA card found at 0x%05X (rev 0x%02X)\n",
                                   isaAddresses[i], rev);
                            fdoExt->PhysicalBase.QuadPart = isaAddresses[i];
                            fdoExt->MappedLength = CY_ISA_WINDOW;
                            fdoExt->BusIndex = 0;
                            isaFound = TRUE;
                            MmUnmapIoSpace(testBase, CY_ISA_WINDOW);
                            break;
                        }

                        MmUnmapIoSpace(testBase, CY_ISA_WINDOW);
                    }
                }

                if (!isaFound) {
                    CyWarn("No ISA card found at any standard address\n");
                    fdoExt->PhysicalBase.QuadPart = CY_DEFAULT_MEMBASE;
                    fdoExt->MappedLength = CY_ISA_WINDOW;
                    fdoExt->BusIndex = 0;
                }
            }

            /* Set the global BusIndex for CyReadReg/CyWriteReg.
             * Must be set BEFORE any register access (chip scan,
             * channel init, ISR). */
            g_CyBusIndex = fdoExt->BusIndex;
        }

        /* Map the physical memory into kernel virtual address space.
         * MmNonCached: hardware registers must not be cached — every
         * read must hit the device, not a stale CPU cache line. */
        fdoExt->CardBase = (PUCHAR)MmMapIoSpace(
            fdoExt->PhysicalBase, fdoExt->MappedLength, MmNonCached);

        if (!fdoExt->CardBase) {
            CyError("MmMapIoSpace failed\n");
            status = STATUS_INSUFFICIENT_RESOURCES;
            break;
        }

        /* Scan for CD1400 chips */
        if (CyScanForChips(fdoExt) == 0) {
            MmUnmapIoSpace(fdoExt->CardBase, fdoExt->MappedLength);
            fdoExt->CardBase = NULL;
            status = STATUS_DEVICE_DOES_NOT_EXIST;
            break;
        }

        /* Create child PDOs for each serial port */
        status = CyCreateChildPDOs(fdoExt);
        if (!NT_SUCCESS(status)) {
            MmUnmapIoSpace(fdoExt->CardBase, fdoExt->MappedLength);
            fdoExt->CardBase = NULL;
            break;
        }

        fdoExt->Started = TRUE;
        CySetPnPState(&fdoExt->Common, CyStarted);

        /* Tell PnP manager to query us for children */
        IoInvalidateDeviceRelations(fdoExt->UnderlyingPDO, BusRelations);

        CyInfo("FDO START complete — %lu chips, %lu ports\n",
                 fdoExt->NumChips, fdoExt->NumPDOs);
        break;


    /* ================================================================
     * IRP_MN_QUERY_DEVICE_RELATIONS (BusRelations)
     * ================================================================
     * Return an array of child PDO pointers. The PnP manager uses
     * this to discover our serial ports and load drivers for them.
     *
     * CRITICAL: ObReferenceObject on each PDO. The PnP manager
     * will ObDereferenceObject when done. If we forget, the PDO
     * gets freed while PnP still holds a pointer → BSOD.
     *
     * Confirmed from original cyclom-y.sys imports: ObfReferenceObject.
     * ================================================================ */
    case IRP_MN_QUERY_DEVICE_RELATIONS:

        if (irpSp->Parameters.QueryDeviceRelations.Type != BusRelations) {
            /* Not a BusRelations query — forward to lower driver */
            goto FdoForwardDefault;
        }

        CyInfo("FDO QUERY_DEVICE_RELATIONS (BusRelations)\n");

        {
            PDEVICE_RELATIONS   relations;
            ULONG               prevCount, totalCount, allocLen;

            /* There might already be relations from a lower filter.
             * If so, we append our children to the existing list. */
            prevCount = 0;
            if (Irp->IoStatus.Information != 0) {
                prevCount = ((PDEVICE_RELATIONS)
                              Irp->IoStatus.Information)->Count;
            }

            totalCount = prevCount + fdoExt->NumPDOs;
            allocLen = sizeof(DEVICE_RELATIONS) +
                       (totalCount * sizeof(PDEVICE_OBJECT));

            relations = (PDEVICE_RELATIONS)ExAllocatePoolWithTag(
                NonPagedPool, allocLen, CY_POOL_TAG);

            if (!relations) {
                status = STATUS_INSUFFICIENT_RESOURCES;
                break;
            }

            /* Copy existing relations (if any) */
            if (prevCount > 0) {
                RtlCopyMemory(
                    relations->Objects,
                    ((PDEVICE_RELATIONS)Irp->IoStatus.Information)->Objects,
                    prevCount * sizeof(PDEVICE_OBJECT));
            }

            /* Add our child PDOs. CRITICAL: we must ObReferenceObject
             * each PDO we put in the array. The PnP manager will call
             * ObDereferenceObject on each one when it's done processing
             * the relations. If we forget the reference, the PDO's
             * reference count drops to zero and the device object is
             * FREED while PnP still holds a pointer to it → BSOD.
             *
             * This is the most common bus driver bug. The original
             * cyclom-y.sys imports ObfReferenceObject for this reason. */
            for (i = 0; i < fdoExt->NumPDOs; i++) {
                relations->Objects[prevCount + i] = fdoExt->ChildPDOs[i];
                ObReferenceObject(fdoExt->ChildPDOs[i]);
            }
            relations->Count = totalCount;

            /* Free the OLD relations structure that was passed to us
             * (if any). We've already copied its contents into our
             * new, larger array. The PnP manager expects exactly one
             * DEVICE_RELATIONS block in IoStatus.Information — if we
             * don't free the old one, it leaks. */
            if (Irp->IoStatus.Information != 0) {
                ExFreePool((PVOID)Irp->IoStatus.Information);
            }

            /* Store our new relations array in the IRP.
             * The PnP manager reads this from IoStatus.Information. */
            Irp->IoStatus.Information = (ULONG_PTR)relations;
            Irp->IoStatus.Status = STATUS_SUCCESS;
        }

        /* Forward to lower driver. We've already filled in our
         * children, but a lower filter might want to add its own.
         * IoSkipCurrentIrpStackLocation reuses our stack location
         * for the next driver (no copy needed since we're done).
         *
         * IMPORTANT: we return directly here — we DON'T fall through
         * to the IoCompleteRequest at the end of the switch. The
         * lower driver will complete the IRP. */
        IoSkipCurrentIrpStackLocation(Irp);
        status = IoCallDriver(fdoExt->LowerDevice, Irp);
        IoReleaseRemoveLock(&fdoExt->Common.RemoveLock, Irp);
        return status;


    /* ================================================================
     * IRP_MN_REMOVE_DEVICE
     * ================================================================
     * Clean up everything. Delete child PDOs, unmap memory, detach
     * from the device stack, delete our FDO.
     * ================================================================ */
    case IRP_MN_REMOVE_DEVICE:

        CyInfo("FDO REMOVE_DEVICE\n");

        CySetPnPState(&fdoExt->Common, CyRemoved);

        /* Delete child PDOs that weren't already removed by PnP.
         * The PnP manager sends REMOVE_DEVICE to each child PDO
         * independently. If it already did, the PDO's PnP state
         * is CyRemoved and we must NOT call IoDeleteDevice again
         * (double-delete → BSOD). (Audit B3 fix) */
        for (i = 0; i < fdoExt->NumPDOs; i++) {
            if (fdoExt->ChildPDOs[i]) {
                PCY_PDO_EXT childExt = CyGetPdo(fdoExt->ChildPDOs[i]);
                if (childExt->Common.PnPState != CyRemoved) {
                    IoDeleteDevice(fdoExt->ChildPDOs[i]);
                }
                fdoExt->ChildPDOs[i] = NULL;
            }
        }
        fdoExt->NumPDOs = 0;

        /* Unmap the CD1400 shared memory window.
         * After this call, ALL child PDO ChipBase pointers become
         * invalid. This is why we must delete/stop all children BEFORE
         * unmapping. Any child that tries to access ChipBase after
         * this point will read from unmapped memory → BSOD. */
        if (fdoExt->CardBase) {
            MmUnmapIoSpace(fdoExt->CardBase, fdoExt->MappedLength);
            fdoExt->CardBase = NULL;
        }

        /* Forward the REMOVE IRP to the lower driver (PCI bus driver).
         * The PCI driver releases its resources (BAR, interrupt line).
         * We must forward BEFORE detaching, because after IoDetachDevice
         * we can no longer reach the lower driver. */
        Irp->IoStatus.Status = STATUS_SUCCESS;
        IoSkipCurrentIrpStackLocation(Irp);
        status = IoCallDriver(fdoExt->LowerDevice, Irp);

        /* IoReleaseRemoveLockAndWait blocks until ALL outstanding
         * remove lock acquisitions are released. This guarantees
         * that no IRP handler is still running when we delete the
         * device object. Without this, a concurrent Read/Write IRP
         * could be accessing the device extension while we free it.
         *
         * Sequence: we acquired the lock at the top of CyDispatchPnP.
         * This call releases OUR lock AND waits for any others. */
        IoReleaseRemoveLockAndWait(&fdoExt->Common.RemoveLock, Irp);

        /* Shut down WPP tracing before destroying the driver object.
         * Must be called while DriverObject is still valid. */
        WPP_CLEANUP(DevObj->DriverObject);

        /* Detach our FDO from the device stack. After this call,
         * fdoExt->LowerDevice is stale — don't use it.
         * Then delete our FDO. After IoDeleteDevice, fdoExt and
         * DevObj are freed memory — don't touch them.
         *
         * Order matters: detach THEN delete. If we delete first,
         * the I/O manager may try to detach a deleted object. */
        IoDetachDevice(fdoExt->LowerDevice);
        IoDeleteDevice(DevObj);

        /* Return directly — DevObj and fdoExt are freed.
         * DO NOT access any field after this point. */
        return status;


    /* ================================================================
     * IRP_MN_QUERY_STOP / CANCEL_STOP / STOP
     * ================================================================ */
    case IRP_MN_QUERY_STOP_DEVICE:
        CyInfo("FDO QUERY_STOP\n");
        CySetPnPState(&fdoExt->Common, CyStopPending);
        Irp->IoStatus.Status = STATUS_SUCCESS;
        goto FdoForwardDefault;

    case IRP_MN_CANCEL_STOP_DEVICE:
        CyInfo("FDO CANCEL_STOP\n");
        CyRestorePnPState(&fdoExt->Common);
        Irp->IoStatus.Status = STATUS_SUCCESS;
        goto FdoForwardDefault;

    case IRP_MN_STOP_DEVICE:
        CyInfo("FDO STOP_DEVICE\n");
        CySetPnPState(&fdoExt->Common, CyStopped);
        fdoExt->Started = FALSE;
        Irp->IoStatus.Status = STATUS_SUCCESS;
        goto FdoForwardDefault;


    /* ================================================================
     * IRP_MN_QUERY_REMOVE / CANCEL_REMOVE
     * ================================================================ */
    case IRP_MN_QUERY_REMOVE_DEVICE:
        CyInfo("FDO QUERY_REMOVE\n");
        CySetPnPState(&fdoExt->Common, CyRemovePending);
        Irp->IoStatus.Status = STATUS_SUCCESS;
        goto FdoForwardDefault;

    case IRP_MN_CANCEL_REMOVE_DEVICE:
        CyInfo("FDO CANCEL_REMOVE\n");
        CyRestorePnPState(&fdoExt->Common);
        Irp->IoStatus.Status = STATUS_SUCCESS;
        goto FdoForwardDefault;

    case IRP_MN_SURPRISE_REMOVAL:
        CyInfo("FDO SURPRISE_REMOVAL\n");
        CySetPnPState(&fdoExt->Common, CySurpriseRemoved);
        Irp->IoStatus.Status = STATUS_SUCCESS;
        goto FdoForwardDefault;


    /* ================================================================
     * Default — forward to lower driver
     * ================================================================ */
    default:
    FdoForwardDefault:
        IoSkipCurrentIrpStackLocation(Irp);
        status = IoCallDriver(fdoExt->LowerDevice, Irp);
        IoReleaseRemoveLock(&fdoExt->Common.RemoveLock, Irp);
        return status;
    }

    /* For cases that break out of the switch (START, relations alloc
     * failure): complete the IRP here */
    Irp->IoStatus.Status = status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    IoReleaseRemoveLock(&fdoExt->Common.RemoveLock, Irp);
    return status;
}


/* ====================================================================
 * CyDispatchPower — MOVED TO cypower.c
 * ====================================================================
 * The full power management implementation with sleep/resume state
 * save/restore is in cypower.c. The stub that was here has been
 * removed to prevent duplicate symbol linker errors.
 * ==================================================================== */
